### ISSUE TITLE
Inconsistent formatting for field labels does not accurately show which fields are required

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#101]
Some required fields (such as "Name Printed on Badge" and "Name on ID") are not bold, despite being required fields. This should be fixed to be consistent with user expectations, and our own in-page explanation of "Bold fields are required."

Additionally, I think the only (currently) optional field is "Your Phone Number." Perhaps we should more clearly indicate this field is optional (e.g. add "(optional)" to the field label)?

**Comment by kitsuta** [comment]
"Name printed on badge" and "Want to volunteer?" are also optional fields.

**Comment by ianlayton** [comment]
Name printed on badge needs to be required please.

**Comment by kitsuta** [comment]
Sure! Just so you know, the system currently just uses the attendee's first and last name if they don't have a badge printed name by the time it's printed.
