### ISSUE TITLE
"State/Region" field is not being properly cleared when changing countries

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#102]
The `State/Region` field is not being properly cleared out when changing countries. Changing from a country with a corresponding `State/Region` dropdown (e.g. United States) and an option selected (e.g. Wisconsin) to a country without such a dropdown (e.g. China) retains the text selected from the dropdown. This text lingers even when selecting another country with a dropdown (e.g. Canada) before selecting one without, as shown by these steps:

Enter "United States" as `Country`.
Select "Wisconsin" from `State/Region` dropdown
Enter "Canada" as `Country`, but do not select an option from the now-cleared dropdown.
Enter "China" as `Country`. Observe that the "Wisconsin" text re-populates the field.

![mff lingering state field](https://cloud.githubusercontent.com/assets/28108495/25568327/ea50eb5c-2dc5-11e7-9546-6c1dbe544fe4.png)

**Comment by kitsuta** [comment]
Fixed by the same fix as #107.
