### ISSUE TITLE
(Question) Handling for invalid mailing address?

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#103]
Do we have a way to verify an entered address is valid? How do we handle addresses that turn out to be invalid, either in the system or on the human-side? In what situations (technical and real-world) would an invalid address be a problem?

**Comment by kitsuta** [comment]
I don't know the answer to the business-process side of these questions, but the form does only basic normalization -- it doesn't actually check to see if the address is real. Attendees can use the confirmation link to change their address if they typoed during prereg or if their address changes.

**Comment by jmdawson** [comment]
This is acceptable for now. In the future, we can consider integrating some existing tools for domestic address validation.

**Comment by ianlayton** [comment]
Business wise, it's not an issue really. We rarely use the mailing address anyways and I make it a habit to confirm via email that it's correct.
