### ISSUE TITLE
Date of Birth fields accept (and then truncate) leading zeroes

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#113]
Another minor issue with the DOB fields: Leading 0's are accepted as valid in the month and day fields (and then truncated) as long as the last two digits are otherwise valid. For example, you can enter "0000010" as the month, which will then be truncated to "10." Interestingly, the relevant error message will appear while entering the leading 0's, then disappear after ending the string with a valid entry, suggesting that the check for data validity is truncating leading 0's as well (we're probably assigning the string to an integer value, which inherently truncates it).

Oddly, this does not happen for the year field; "00001990" will not be accepted.

**Comment by kitsuta** [comment]
Huh, this sounds like an interesting quirk of the datetextentry plugin we're using. I wouldn't really call it undesirable behavior though -- in fact, I'd say that it was probably designed this way to accommodate people (and form autofills) who are used to entering two-digit fields (like '08').

**Comment by jmdawson** [comment]
Year field is pretty picky about being 4 digits, as I recall. This is fine until we run into a Y10k problem. If MFF is still running and running RAMS at that point, they'll have to celebrate.

Until then, however, I think this behavior is acceptable.

**Comment by kitsuta** [comment]
Oh yeah, just an FYI -- all this stuff is stored in the backend as a datetime object, so the date format can be changed on the frontend with minimal code changes.
