### ISSUE TITLE
Duplicate e-mail addresses are permitted

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#114]
This may be intended behavior, but I wanted to call it out so we make a conscious decision on it. Currently, the same e-mail address can be used for multiple attendees. I know some similar systems sometimes forbid using an identical e-mail address (though this usually pertains to password recovery issues, which we don't have to deal with), and I don't know if it might cause problems down the line in some other process.

This could cause problems in some unforseen future situation where we use this data. For example, if we were to use past registration information to automatically create some kind of MFF account (like MCFC does), we wouldn't (or shouldn't) be able to make multiple accounts for the same e-mail address.

If we were to change this, however, the same e-mail address should be allowed to be used for registrations in the same group. For example, a parent registering their children might want all the confirmations routed to their single address. Given this and the minute benefits we might see from changing the system, it is probably best to leave it as-is.

**Comment by ianlayton** [comment]
This is by design
