### ISSUE TITLE
"Preregistration deleted" message when aborting a duplicate registration can be misleading

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#116]
When attempting to register with the same name AND e-mail address as a previous registration (both must be true to trigger this), a warning page appears asking if you're sure you're a different person. If the user selects the "Well never mind then!" option, they are taken back to an empty registration form, with a "Preregistration deleted" banner message at the top.

A user might draw the wrong conclusion from this message, and worry that their old registration was deleted for some reason. While this will probably be a very rare occurrence in the first place, it wouldn't hurt to either change the message, or just not show it in the first place.

**Comment by kitsuta** [comment]
Whoops, good point! I should be able to fix this.
