### ISSUE TITLE
Cannot register as attendee

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#122]
Javascript error appears to prevent the badge name field from rendering, which causes reg to fail the verification checks.

`form:541 Uncaught TypeError: Cannot read property 'parents' of null
    at HTMLDocument.<anonymous> (form:541)
    at fire (combined.js:35238)
    at Object.fireWith [as resolveWith] (combined.js:35350)
    at Function.ready (combined.js:35556)
    at HTMLDocument.completed (combined.js:35572)
(anonymous)	@	form:541
fire	@	combined.js:35238
fireWith	@	combined.js:35350
ready	@	combined.js:35556
completed	@	combined.js:35572
`

`<script type="text/javascript">
    $(function () {
        // Position new field(s)
        if ($('#power').length) {
            $('#power').parents('.form-group').insertBefore($.field('wares').parents('.form-group'))
        }
        // Hide reference to requesting more than four tables and list of prices.
        $("#moretables").hide();
        $("#table_prices").hide();

        // Hides "wares" box because we are not using it
        $.field('wares').parents('.form-group').hide();
        $('p:contains("Please be detailed; include a link to view your wares if possible.")').hide();

        // Rename Description box and help text
        $('label:contains("Description")').text('Merchandise Description');
        $('p:contains("Please keep to one sentence.")').text('This will be used both for dealer selection (if necessary) and in all dealer listings.')
    });
</script>`

541 specifically points to this line: ` $.field('wares').parents('.form-group').hide();`

**Comment by jmdawson** [comment]
Bug in implementation of #121 

Have temporarily rolled both staging and almost-prod back to prior commit in interim.

**Comment by kitsuta** [comment]
Should be fixed. Whoops!
