### ISSUE TITLE
Minor message

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#127]
Currently

Attendees under 18 MUST bring a signed (and notarized if not accompanied by parent or guardian during badge pickup) parental consent form.

Should read

Attendees under 18 MUST bring a signed and notarized parental consent form if not accompanied by parent or guardian during badge pickup.

Keep link as it is.

We don't require the signed form if the parent/guardian is attending with the child.

**Comment by jmdawson** [comment]
5 minutes.
