### ISSUE TITLE
Very long life session cookie not clearing out when closing browser

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#128]
It appear that not only is the session cookie is being set to 3 day, it isn't getting cleared out when closing down the browser. This can not only leave someone's previous registration data accessible but also can leave someone logged into the admin section even after the browser is closed.

Please reduce the session cookie lifetime down to something more reasonable (like an hour) or make it so the cookie dies when the browser is closed.

![session](https://cloud.githubusercontent.com/assets/11669617/25928661/1ad7d416-35c3-11e7-8fd8-70d2d4ba1037.jpeg)

**Comment by jmdawson** [comment]
Addressing only the "someone else's registration" part: 
![nomorereglist](https://cloud.githubusercontent.com/assets/910490/25979851/80f48140-3690-11e7-9954-197e4d590745.jpeg)

Admin side will have to wait.

**Comment by ianlayton** [comment]
Thank you...that fixes the issue that's more likely to be stumbled acrossed by a random person and cause an issue.

**Comment by kitsuta** [comment]
Admin part of this issue was split into https://github.com/MidwestFurryFandom/rams/issues/131 (thanks @jmdawson!)
