### ISSUE TITLE
Update main page to be more attendee-friendly

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#129]
Operating under the theory that attendees may end up on the main reg.furfest.org/rams/common/ page instead of landing directly on a reg or dealer form, update the main page for...I dunno, whateverness.

**Comment by jmdawson** [comment]
Now with more buttons. This is the intent I divined from the file sent to me.  If @ianlayton would like something else, I will need details.
![indexasdescribed](https://cloud.githubusercontent.com/assets/910490/25980616/62fb7b76-3695-11e7-9457-aef87cff77d2.jpeg)

**Comment by ianlayton** [comment]
Yep...thank you.

**Comment by ianlayton** [comment]
Just noticed that the link to the "If Registered" is pointing to registration form, not the check page. This is totally my fault for putting the wrong link in there. This is not an emergency, but can this get fixed at the next push please.

**Comment by kitsuta** [comment]
Done.

**Comment by jmdawson** [comment]
Deployed
