### ISSUE TITLE
Responder emails need to be updated.

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#136]
Please update with the following before we go live.

[emails.zip](https://github.com/MidwestFurryFandom/rams/files/998976/emails.zip)

**Comment by jmdawson** [comment]
Can you please provide an executive summary of the requested changes? Is anything here business critical, or inconvenient?  Is anything in here worth delaying the launch for?

**Comment by ianlayton** [comment]
Um...saying I sent you these emails to you on the 8th and they weren't changed...

Please make the changes.

**Comment by ianlayton** [comment]
I apologize for not catching that they weren't changed until now. I'll make sure to use this system from now on to make sure stuff isn't lost or buried in emails.

As for the changes, the current emails uses wrong terminology and links, so yes, it really does need to be changed before we go live please.

**Comment by jmdawson** [comment]
i'll look into these tomorrow.

**Comment by ianlayton** [comment]
Thank you, it's fine for the soft launch, but needs to be changed before
the full launch please.

-- 
Ian Layton

**Comment by jmdawson** [comment]
Needs customer validation.

**Comment by ianlayton** [comment]
Emails look good to me as well, thank you for doing the updates.
