### ISSUE TITLE
Consider styling the First/Last Name & Legal Name for greater clarity

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#138]
Some attendees find the two sets of names and the checkbox confusing. Perhaps restyling them into a bordered div would help enhance clarity. Maybe we want to move the link to a different place?  This is one of those "shop it around" things.

**Comment by jmdawson** [comment]
Comment from attendee (paraphrased): "Exactly" is the key word of confusion.  Lots of things that appear EXACTLY on ID aren't really what we mean.

**Comment by kitsuta** [comment]
Yeah, this is a brand-new feature so the UX on it is not 100% there.

**Comment by jmdawson** [comment]
Been good enough for years now. Closing.
