### ISSUE TITLE
As an attendee, I would like to only see fields relevant to the badge type I have selected

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#14]
WARNING: Currently missing specs for what fields those are.

**Comment by ianlayton** [comment]
T-shirt size is only needed if the user selects a sponsor or shiny level. That would be the only field that is level dependent.

**Comment by kitsuta** [comment]
OK, thank you! This is actually already built in code-wise, but I'll leave this issue open until I make sure I've got the config set up right.
