### ISSUE TITLE
No Hacking Allowed error message

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#144]
> When I tried to put an entry in, I got an error message saying “No hacking allowed” and nothing else. No clue what’s causing that.

Occurred while RAMS in at-con mode. No further information.

**Comment by kitsuta** [comment]
IIRC this error message is about trying to get an 'unapproved' badge type through the at-door reg page. It prevents people from trying to register for a staff badge, that sort of thing. This SHOULD be a config option although it may require a small code change.

**Comment by kitsuta** [comment]
Update: This is also happening for MAGStock, which has really standard config set up, so it's definitely a bug.
