### ISSUE TITLE
Dealer cannot add assistant after paying

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#152]
This user is consistently getting a "The prices have gone up since you tried to add the badge" error and is unable to register an assistant after having paid for her table.

<img width="1280" alt="screen shot 2017-06-15 at 11 33 49 pm" src="https://user-images.githubusercontent.com/910490/27226271-cb2e3e7e-5263-11e7-9fb4-51946c614ca1.png">
<img width="1280" alt="screen shot 2017-06-15 at 11 33 08 pm" src="https://user-images.githubusercontent.com/910490/27226272-cb33996e-5263-11e7-898e-5920a5c36a58.png">
<img width="1280" alt="screen shot 2017-06-15 at 11 32 18 pm" src="https://user-images.githubusercontent.com/910490/27226273-cb364f56-5263-11e7-82c5-dffe5828f99b.png">

**Comment by jmdawson** [comment]
Message is generated here:

```
 @credit_card
    def pay_for_extra_members(self, session, payment_id, stripeToken):
        charge = Charge.get(payment_id)
        [group] = charge.groups
        badges_to_add = charge.dollar_amount // c.GROUP_PRICE
        if charge.dollar_amount % c.GROUP_PRICE:
            message = 'Our preregistration price has gone up since you tried to add the badges; please try again'
        else:
            message = charge.charge_cc(session, stripeToken)

        if message:
            raise HTTPRedirect('group_members?id={}&message={}', group.id, message)
        else:
            session.assign_badges(group, group.badges + badges_to_add)
            group.amount_paid += charge.dollar_amount
            session.merge(group)
            if group.is_dealer:
                send_email(c.MARKETPLACE_EMAIL, c.MARKETPLACE_EMAIL, 'Dealer Paid for Extra Members',
                           render('emails/dealers/payment_notification.txt', {'group': group}), model=group)
            raise HTTPRedirect('group_members?id={}&message={}', group.id, 'You payment has been accepted and the badges have been added to your group')


```

**Comment by jmdawson** [comment]
Blame for the math that triggers this message: https://github.com/MidwestFurryFandom/rams/commit/421d87046414376df5098df1ccbe5c263c6cbc6f

**Comment by jmdawson** [comment]
I don't see how this is ever going to work for adding badges after the fact. // is a floor function, and a new badge will be less than the original group price...pretty much always, so you should end up with badges_to_add =0, and then you'll also get.... $50 % GROUP_PRICE, which, in example, is $50 % $170 which is just $50, and since that's non-zero, you should get the message.

**Comment by jmdawson** [comment]
This seems to work:
`Capolitana-2:quickstart crimson$ git diff ~/mff-rams/dev/rams/development.ini src/uber/development.ini
diff --git a/Users/crimson/mff-rams/dev/rams/development.ini b/src/uber/development.ini
index 896b0b1..3ceb854 100644
--- a/Users/crimson/mff-rams/dev/rams/development.ini
+++ b/src/uber/development.ini
@@ -81,6 +81,7 @@ badge_price_waived = ""
 
 [badge_prices]
 initial_attendee = 50
+group_discount = 0
 [[single_day]]
 Friday = 25
 Saturday = 35
`

**Comment by jmdawson** [comment]
Setting group_discount = 0 in development.ini makes this problem go away.

**Comment by jmdawson** [comment]
Not so fixed as I thought. Just added a dealer and got a odd 500:
`500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 349, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/uber/uber/site_sections/preregistration.py", line 23, in wrapped
    return func(self, *args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 187, in charge
    return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken)
  File "/app/plugins/uber/uber/site_sections/preregistration.py", line 427, in pay_for_extra_members
    raise HTTPRedirect('group_members?id={}&message={}', group.id, 'You payment has been accepted and the badges have been added to your group')
uber.utils.HTTPRedirect: (['http://rams.test.furfest.org/rams/preregistration/group_members?id=7006077c-47dd-44e7-a78f-1b1556786d5c&message=You%20payment%20has%20been%20accepted%20and%20the%20badges%20have%20been%20added%20to%20your%20group'], 303)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()
psycopg2.IntegrityError: duplicate key value violates unique constraint "uq_attendee_badge_num"
DETAIL:  Key (badge_num)=(1052) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 257, in with_session
    session.commit()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 465, in commit
    t[1].commit()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1632, in commit
    self._do_commit()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit
    self.connection._commit_impl()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "uq_attendee_badge_num"
DETAIL:  Key (badge_num)=(1052) already exists.

`

**Comment by jmdawson** [comment]
Ah-hah, found it in the feed of changes.
`14:13 on October 21 2017	Test Developer	Attendee	<Attendee full_name='Email Recipient'>	updated	badge_status=''Not Attending' -> 'Not Attending'', badge_num='None -> 1052'`

**Comment by jmdawson** [comment]
Confirmed: Stripe takes the payment while RAMS throws this error. This is...blocking.

**Comment by jmdawson** [comment]
```
uber_db=# select id, badge_num, first_name, last_name, badge_printed_name from attendee order by badge_num desc limit 50;
|                  id                  | badge_num | first_name |    last_name    |    badge_printed_name    |
|--------------------------------------+-----------+------------+-----------------+--------------------------|
| 9295221f-248a-4a4d-8bfd-9806f6866397 |           | Discount   | Test            | |
| 78e13c56-18ce-43c3-aa3b-930cf1c8530b |           | Test       | Tester          | Testerersersr|
| 2a29a9fc-51e8-445c-a292-b9298240586a |           | Ian        | Layton          | Rama Email test|
| 148a90b9-86a1-42bb-a940-c3e7a6738d68 |           | Analytic   | Test            | Analytics|
| b76f14f7-1f4e-4a32-912f-96c8a7afd357 |           |            |                 | |
| 8bff1b03-7dbb-460b-aa48-c6bd0539c305 |           |            |                 | |
| 870289e3-3d3d-4dfa-81a5-790d2d434deb |           |            |                 | |
| ac45d73a-bb61-4198-8131-7b2a2fe923e3 |           | Asdfs      | Asdfas          | asdasdfasdf|
| 8b3c6a91-e481-49e9-89b1-71983d337a0a |           | Ian        | Layton          | Rama 1|
| aa50f3c3-c5c8-430f-9fec-5cdb98552b3b |           | Guy        | Threepbrush     | |
| 13114b6b-23d9-4f0e-b704-52ea58f766a8 |           | Test       | Developer       | |
| bf64aed7-3c67-425e-89eb-ab00d8aae927 |           | Fred       | Waitlist        | ShareBoy|
| 5d58eb9d-2b37-4b6e-8745-bc11ae700675 |           | Ian        | Layton          | |
| bc7d9c31-4c94-43c6-b023-22647f71d469 |           | Test       | Minor           | |
| d9c4e6ec-e4df-48ea-8042-f16ca1d710ad |           | Ian        | Layton          | Rama Group Leader|
| ddcec7c6-91ad-4ff3-a909-11ebfb4aa4c0 |           | Ian        | Layton          | Rama Asst 1|
| 3332bbf5-3180-4635-9461-f3044abab74c |           | Ian        | Layton          | Rama Group Leader 2|
| 5434c8e1-caf7-4474-b4c2-0216c0c6a89e |           |            |                 | |
| ed047943-afa7-4d51-b2a7-75fa9de40671 |           |            |                 | |
| 62dade91-55ba-448b-aa5c-2db7e1191c7f |           |            |                 | |
| 60fa09ee-8946-4158-a3b6-5ffc6378f966 |           | Ian        | Layton          | Rama Group Leader 4|
| 7bbc2207-e17a-4e43-8f6a-e936c14a4ab9 |           | Ian        | Layton          | Rama 4 Asst 2|
| 425e850f-88de-4f67-91f8-18df9dea1257 |           | Robert     | Panelist        | Rob Panelist|
| 8f47599a-abb4-410a-ab20-2e69b0973f8a |           | Dev        | Cheater         | |
| 53084fbb-3fc4-4023-a1c7-1006e767ac17 |           | Miko       | Mouse           | |
| d6cd67c7-f83b-4f9b-99ff-eac425481a35 |           | Skyler     | Ringtail        | |
| 1a9bd308-f2d9-4881-bd10-daf48101f7d9 |           | Testsing   | Fixes           | |
| a5a6ffe1-f825-41ca-b669-6329700e26f1 |           | Not        | Registered?     | |
| 50c89ce8-052a-4bd2-8b16-e26603aabc48 |           | Total      | Test            | |
| 405fd8fb-f0f0-4ee6-b9f9-e071087086fe |           | Not        | Going           | |
| 0ca80a5a-6383-48d4-809e-70a134acf544 |           | Greedy     | Somna           | |
| be23bae5-27b7-4fc4-b404-5a86d2ce84a4 |           | New        | Reg             | |
| d91197ad-fca9-436d-976e-729674d5acd6 |           | No         | Attend          | |
| 5df12a29-d125-456e-a0f6-a00481d497e8 |           | Ian        | Layton          | |
| 4273c9ae-f4ad-4e74-92cd-a6be171a3f51 |           | Brian      | Layton          | Rama Single Group Leader|
| 1ae38441-a836-4ba8-8705-63231bb28c56 |           | Woke       | Rapper          | WokkaTester|
| 2a18bacc-f597-40f5-a554-12bc496dea57 |           | Am         | Error           | |
| a8540ab1-9b79-427b-8424-863f2b8beb25 |           | Test       | BadgeNum        | cdkz|
| 6f745592-1d98-48fd-902f-438ebc638a30 |           | Scott      | Fuller          | Skyler Ringtail|
| 74658661-abc5-4f95-afe5-56bca512f787 |           | Sunday     | Attendee        | SundayAttendee|
| 232dbb1d-bc24-4268-8871-e3ee57960361 |     10000 | Sunday     | Attendee        | OneDay - Sunday|
| 9d4a18c1-1e8b-44fa-b2e9-6faeccc99dd8 |      1063 | Asldkjf    | 2823            | SLdkjfaslkdfja8fuas0f8|
| d1b8963d-b628-4d16-8929-c3f9ef42edc2 |      1062 | Test       | BadgeNumbering6 | BadgeNumbering6|
| b7e45f7b-551a-4b10-871a-28e8b5b3403b |      1061 | Test       | BadgeNumbering3 | BadgeNumbering3|
| 8f391d31-1d6d-4185-9daf-d2e65301330d |      1060 | Test       | BadgeNumbering4 | BadgeNumbering4|
| bd9bf216-b95f-40f9-9e95-e56a056b859a |      1059 | Victoria   | BadgeNumbering5 | Victoria Earl|
| 469ee541-0e82-4139-a694-4be71655f5f8 |      1058 | Test       | BadgeNumbering  | BadgeNumbering|
| 74adfb9d-1167-42cd-b4ba-387007b9bcb9 |      1057 | Test       | BadgeNumbering2 | BadgeNumbering2|
| c1f54f61-9bac-4922-8076-7dc5cc1b8487 |      1056 | Test       | Birthdate       | TestDOB|
| 3608377e-1490-41c9-b50c-b6bc4dc7bc01 |      1055 | Second     | Reg             | Second Reg|
(50 rows)
```

**Comment by kitsuta** [comment]
This bug occurs regardless of whether you're on the master branch or mff-staging. We definitely want to fix this as soon as possible, but the code changes did not create this -- data changes on the staging server did.

Looks like you can trigger it by reducing the number of badges in a group after those badges have been numbered.

**Comment by kitsuta** [comment]
I believe I managed to fix this.

**Comment by jmdawson** [comment]
I believe the logic is too aggressive.
<img width="769" alt="screen shot 2017-10-30 at 07 43 13" src="https://user-images.githubusercontent.com/910490/32171444-13943ef0-bd46-11e7-88f8-e3ec863dce13.png">

**Comment by kitsuta** [comment]
It looks like it's only doing that for this specific operation -- badges added in other ways don't fail to fill in gaps like that. Unfortunately, I can't figure out why it might be failing in this one case; no matter what I do, new group members' badges are only being numbered starting at the highest numbered badge already in the group, which was one of the reasons this was a problem in the first place.
