### ISSUE TITLE
Random slowdowns

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#155]
Every so often, when I’m on the system, it sometimes just sits and spins for 20+ seconds waiting for page while most of the time, it’s running completely fine, giving me the page in mere seconds. Sunday, I even got a “slowdown” page when I went into the system. I’ve seen this happen mainly on the admin side but have also seen it happen with the front page. This has also happened on multiple computers, networks and times of day. 

I’ve yet to hear an attendee mention it though, so I’m not 100% sure it’s anything system related

It seems sporadic and I don't think I can predict when it will happen.

**Comment by ianlayton** [comment]
Wanted to bring this back in attention as we're still seeing random slowdowns in page responses for the system. Had a member report that they receive the slowdown page.

**Comment by ianlayton** [comment]
Slow downs seem to be coming back again.

**Comment by jmdawson** [comment]
We finally fixed this in 2019.
