### ISSUE TITLE
Adding at-door attendee fails with stack trace

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#158]
Stack Trace in Browser
Please contact us via https://www.furfest.org if you're not sure why you're seeing this page.
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: invalid input syntax for integer: "None"
LINE 4: WHERE attendee.badge_num = 'None' AND attendee.badge_type = ...
                                   ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 349, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 29, in with_check
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/site_sections/registration.py", line 97, in form
    message = check(attendee)
  File "/app/plugins/uber/uber/utils.py", line 123, in check
    message = validator(model)
  File "/app/plugins/uber/uber/model_checks.py", line 314, in dupe_badge_num
    if existing.count():
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 3089, in count
    return self.from_self(col).scalar()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
    ret = self.one()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for integer: "None"
LINE 4: WHERE attendee.badge_num = 'None' AND attendee.badge_type = ...
                                   ^
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT attendee.id AS attendee_id, attendee.watchlist_id AS attendee_watchlist_id, attendee.group_id AS attendee_group_id, attendee.placeholder AS attendee_placeholder, attendee.first_name AS attendee_first_name, attendee.last_name AS attendee_last_name, attendee.legal_name AS attendee_legal_name, attendee.email AS attendee_email, attendee.birthdate AS attendee_birthdate, attendee.age_group AS attendee_age_group, attendee.international AS attendee_international, attendee.zip_code AS attendee_zip_code, attendee.address1 AS attendee_address1, attendee.address2 AS attendee_address2, attendee.city AS attendee_city, attendee.region AS attendee_region, attendee.country AS attendee_country, attendee.no_cellphone AS attendee_no_cellphone, attendee.ec_name AS attendee_ec_name, attendee.ec_phone AS attendee_ec_phone, attendee.cellphone AS attendee_cellphone, attendee.interests AS attendee_interests, attendee.found_how AS attendee_found_how, attendee.comments AS attendee_comments, attendee.for_review AS attendee_for_review, attendee.admin_notes AS attendee_admin_notes, attendee.public_id AS attendee_public_id, attendee.badge_num AS attendee_badge_num, attendee.badge_type AS attendee_badge_type, attendee.badge_status AS attendee_badge_status, attendee.ribbon AS attendee_ribbon, attendee.affiliate AS attendee_affiliate, attendee.shirt AS attendee_shirt, attendee.can_spam AS attendee_can_spam, attendee.regdesk_info AS attendee_regdesk_info, attendee.extra_merch AS attendee_extra_merch, attendee.got_merch AS attendee_got_merch, attendee.reg_station AS attendee_reg_station, attendee.registered AS attendee_registered, attendee.checked_in AS attendee_checked_in, attendee.paid AS attendee_paid, attendee.overridden_price AS attendee_overridden_price, attendee.amount_paid AS attendee_amount_paid, attendee.amount_extra AS attendee_amount_extra, attendee.payment_method AS attendee_payment_method, attendee.amount_refunded AS attendee_amount_refunded, attendee.badge_printed_name AS attendee_badge_printed_name, attendee.staffing AS attendee_staffing, attendee.requested_depts AS attendee_requested_depts, attendee.assigned_depts AS attendee_assigned_depts, attendee.trusted_depts AS attendee_trusted_depts, attendee.nonshift_hours AS attendee_nonshift_hours, attendee.past_years AS attendee_past_years, attendee.can_work_setup AS attendee_can_work_setup, attendee.can_work_teardown AS attendee_can_work_teardown, attendee.print_pending AS attendee_print_pending, attendee.times_printed AS attendee_times_printed, attendee.comped_reason AS attendee_comped_reason \nFROM attendee \nWHERE attendee.badge_num = %(badge_num_1)s AND attendee.badge_type = %(badge_type_1)s) AS anon_1'] [parameters: {'badge_num_1': 'None', 'badge_type_1': 51352218}]
Powered by CherryPy 8.9.1

Logs:
rams_db  | ERROR:  invalid input syntax for integer: "None" at character 2650
rams_db  | STATEMENT:  SELECT count(*) AS count_1 
rams_db  | 	FROM (SELECT attendee.id AS attendee_id, attendee.watchlist_id AS attendee_watchlist_id, attendee.group_id AS attendee_group_id, attendee.placeholder AS attendee_placeholder, attendee.first_name AS attendee_first_name, attendee.last_name AS attendee_last_name, attendee.legal_name AS attendee_legal_name, attendee.email AS attendee_email, attendee.birthdate AS attendee_birthdate, attendee.age_group AS attendee_age_group, attendee.international AS attendee_international, attendee.zip_code AS attendee_zip_code, attendee.address1 AS attendee_address1, attendee.address2 AS attendee_address2, attendee.city AS attendee_city, attendee.region AS attendee_region, attendee.country AS attendee_country, attendee.no_cellphone AS attendee_no_cellphone, attendee.ec_name AS attendee_ec_name, attendee.ec_phone AS attendee_ec_phone, attendee.cellphone AS attendee_cellphone, attendee.interests AS attendee_interests, attendee.found_how AS attendee_found_how, attendee.comments AS attendee_comments, attendee.for_review AS attendee_for_review, attendee.admin_notes AS attendee_admin_notes, attendee.public_id AS attendee_public_id, attendee.badge_num AS attendee_badge_num, attendee.badge_type AS attendee_badge_type, attendee.badge_status AS attendee_badge_status, attendee.ribbon AS attendee_ribbon, attendee.affiliate AS attendee_affiliate, attendee.shirt AS attendee_shirt, attendee.can_spam AS attendee_can_spam, attendee.regdesk_info AS attendee_regdesk_info, attendee.extra_merch AS attendee_extra_merch, attendee.got_merch AS attendee_got_merch, attendee.reg_station AS attendee_reg_station, attendee.registered AS attendee_registered, attendee.checked_in AS attendee_checked_in, attendee.paid AS attendee_paid, attendee.overridden_price AS attendee_overridden_price, attendee.amount_paid AS attendee_amount_paid, attendee.amount_extra AS attendee_amount_extra, attendee.payment_method AS attendee_payment_method, attendee.amount_refunded AS attendee_amount_refunded, attendee.badge_printed_name AS attendee_badge_printed_name, attendee.staffing AS attendee_staffing, attendee.requested_depts AS attendee_requested_depts, attendee.assigned_depts AS attendee_assigned_depts, attendee.trusted_depts AS attendee_trusted_depts, attendee.nonshift_hours AS attendee_nonshift_hours, attendee.past_years AS attendee_past_years, attendee.can_work_setup AS attendee_can_work_setup, attendee.can_work_teardown AS attendee_can_work_teardown, attendee.print_pending AS attendee_print_pending, attendee.times_printed AS attendee_times_printed, attendee.comped_reason AS attendee_comped_reason 
rams_db  | 	FROM attendee 
rams_db  | 	WHERE attendee.badge_num = 'None' AND attendee.badge_type = 51352218) AS anon_1
web_1    | failed releasing c.BADGE_LOCK on db error; these errors should not happen in the first place and we do not expect releasing the lock to fail when they do, but we still want to keep going if/when this does occur
web_1    | 
web_1    | Exception encountered
web_1    | Request: POST /rams/registration/form HTTP/1.1
web_1    | Current admin user is: Test Developer
web_1    | Request Params:
web_1    |   ec_phone: 2422424444
web_1    |   id: None
web_1    |   csrf_token: 8aefcd806abc4c0da9d28353782daa2a
web_1    |   badge_status: 215389669
web_1    |   country: United States
web_1    |   region: Vermont
web_1    |   admin_notes: 
web_1    |   extra_merch: 
web_1    |   cellphone: 2828288888
web_1    |   badge_type: 51352218
web_1    |   birthdate: 1919-09-09
web_1    |   for_review: 
web_1    |   found_how: 
web_1    |   regdesk_info: 
web_1    |   amount_paid: 50
web_1    |   city: asdf
web_1    |   amount_refunded: 0
web_1    |   group_opt: 
web_1    |   save: save
web_1    |   same_legal_name: 1
web_1    |   email: crimson@furfest.org
web_1    |   return_to: 
web_1    |   address2: 
web_1    |   first_name: Wakka
web_1    |   ribbon: 154973361
web_1    |   comped_reason: 
web_1    |   address1: asdasdf
web_1    |   badge_printed_name: WakkaPrinterTester
web_1    |   no_override: on
web_1    |   badge_num: None
web_1    |   legal_name: 
web_1    |   comments: 
web_1    |   amount_extra: 0
web_1    |   zip_code: 60148
web_1    |   last_name: Tester
web_1    |   overridden_price: 50
web_1    |   paid: 254570300
web_1    |   ec_name: asdf
web_1    | Session Params:
web_1    | dict_items([('account_id', 'ce8cfba5-d265-460f-9822-74afa42d4f00'), ('paid_preregs', []), ('unpaid_preregs', OrderedDict()), ('csrf_token', '8aefcd806abc4c0da9d28353782daa2a')])
web_1    | Request Headers:
web_1    |   X-FORWARDED-PROTO: http
web_1    |   Content-Length: 638
web_1    |   HOST: localhost
web_1    |   ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
web_1    |   X-REAL-IP: 172.17.0.1
web_1    |   ACCEPT-LANGUAGE: en-US,en;q=0.8
web_1    |   COOKIE: session_id=d11b3f8ea97e63d7fe22342102fa463cd5df4824
web_1    |   Content-Type: application/x-www-form-urlencoded
web_1    |   CACHE-CONTROL: max-age=0
web_1    |   UPGRADE-INSECURE-REQUESTS: 1
web_1    |   CONNECTION: close
web_1    |   Remote-Addr: 172.17.0.4
web_1    |   USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
web_1    |   REFERER: http://localhost/rams/registration/form
web_1    |   ORIGIN: http://localhost
web_1    |   X-FORWARDED-PORT: 80
web_1    |   X-FORWARDED-FOR: 172.17.0.1
web_1    |   ACCEPT-ENCODING: gzip, deflate, br
web_1    |   X-FORWARDED-SSL: off
web_1    | Traceback (most recent call last):
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
web_1    |     context)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
web_1    |     cursor.execute(statement, parameters)
web_1    | psycopg2.DataError: invalid input syntax for integer: "None"
web_1    | LINE 4: WHERE attendee.badge_num = 'None' AND attendee.badge_type = ...
web_1    |                                    ^
web_1    | 
web_1    | 
web_1    | The above exception was the direct cause of the following exception:
web_1    | 
web_1    | Traceback (most recent call last):
web_1    |   File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
web_1    |     response.body = self.handler()
web_1    |   File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
web_1    |     self.body = self.oldhandler(*args, **kwargs)
lb_1     | nginx.1    | localhost 172.17.0.1 - - [22/Sep/2017:02:27:58 +0000] "POST /rams/registration/form HTTP/1.1" 500 7949 "http://localhost/rams/registration/form" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
web_1    |   File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
web_1    |     return self.callable(*self.args, **self.kwargs)
web_1    |   File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
web_1    |     return func(*args, **kwargs)
web_1    |   File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
web_1    |     return func(*args, **kwargs)
web_1    |   File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
web_1    |     retval = func(*args, session=session, **kwargs)
web_1    |   File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
web_1    |     return func(*args, **kwargs)
web_1    |   File "/app/plugins/uber/uber/decorators.py", line 349, in with_rendering
web_1    |     result = func(*args, **kwargs)
web_1    |   File "/app/plugins/uber/uber/decorators.py", line 29, in with_check
web_1    |     return func(*args, **kwargs)
web_1    |   File "/app/plugins/uber/uber/site_sections/registration.py", line 97, in form
web_1    |     message = check(attendee)
web_1    |   File "/app/plugins/uber/uber/utils.py", line 123, in check
web_1    |     message = validator(model)
web_1    |   File "/app/plugins/uber/uber/model_checks.py", line 314, in dupe_badge_num
web_1    |     if existing.count():
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 3089, in count
web_1    |     return self.from_self(col).scalar()
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
web_1    |     ret = self.one()
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2814, in one
web_1    |     ret = self.one_or_none()
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
web_1    |     ret = list(self)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
web_1    |     return self._execute_and_instances(context)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
web_1    |     result = conn.execute(querycontext.statement, self._params)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
web_1    |     return meth(self, multiparams, params)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
web_1    |     return connection._execute_clauseelement(self, multiparams, params)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
web_1    |     compiled_sql, distilled_params
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
web_1    |     context)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
web_1    |     exc_info
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
web_1    |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
web_1    |     raise value.with_traceback(tb)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
web_1    |     context)
web_1    |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
web_1    |     cursor.execute(statement, parameters)
web_1    | sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for integer: "None"
web_1    | LINE 4: WHERE attendee.badge_num = 'None' AND attendee.badge_type = ...
web_1    |                                    ^
web_1    |  [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT attendee.id AS attendee_id, attendee.watchlist_id AS attendee_watchlist_id, attendee.group_id AS attendee_group_id, attendee.placeholder AS attendee_placeholder, attendee.first_name AS attendee_first_name, attendee.last_name AS attendee_last_name, attendee.legal_name AS attendee_legal_name, attendee.email AS attendee_email, attendee.birthdate AS attendee_birthdate, attendee.age_group AS attendee_age_group, attendee.international AS attendee_international, attendee.zip_code AS attendee_zip_code, attendee.address1 AS attendee_address1, attendee.address2 AS attendee_address2, attendee.city AS attendee_city, attendee.region AS attendee_region, attendee.country AS attendee_country, attendee.no_cellphone AS attendee_no_cellphone, attendee.ec_name AS attendee_ec_name, attendee.ec_phone AS attendee_ec_phone, attendee.cellphone AS attendee_cellphone, attendee.interests AS attendee_interests, attendee.found_how AS attendee_found_how, attendee.comments AS attendee_comments, attendee.for_review AS attendee_for_review, attendee.admin_notes AS attendee_admin_notes, attendee.public_id AS attendee_public_id, attendee.badge_num AS attendee_badge_num, attendee.badge_type AS attendee_badge_type, attendee.badge_status AS attendee_badge_status, attendee.ribbon AS attendee_ribbon, attendee.affiliate AS attendee_affiliate, attendee.shirt AS attendee_shirt, attendee.can_spam AS attendee_can_spam, attendee.regdesk_info AS attendee_regdesk_info, attendee.extra_merch AS attendee_extra_merch, attendee.got_merch AS attendee_got_merch, attendee.reg_station AS attendee_reg_station, attendee.registered AS attendee_registered, attendee.checked_in AS attendee_checked_in, attendee.paid AS attendee_paid, attendee.overridden_price AS attendee_overridden_price, attendee.amount_paid AS attendee_amount_paid, attendee.amount_extra AS attendee_amount_extra, attendee.payment_method AS attendee_payment_method, attendee.amount_refunded AS attendee_amount_refunded, attendee.badge_printed_name AS attendee_badge_printed_name, attendee.staffing AS attendee_staffing, attendee.requested_depts AS attendee_requested_depts, attendee.assigned_depts AS attendee_assigned_depts, attendee.trusted_depts AS attendee_trusted_depts, attendee.nonshift_hours AS attendee_nonshift_hours, attendee.past_years AS attendee_past_years, attendee.can_work_setup AS attendee_can_work_setup, attendee.can_work_teardown AS attendee_can_work_teardown, attendee.print_pending AS attendee_print_pending, attendee.times_printed AS attendee_times_printed, attendee.comped_reason AS attendee_comped_reason \nFROM attendee \nWHERE attendee.badge_num = %(badge_num_1)s AND attendee.badge_type = %(badge_type_1)s) AS anon_1'] [parameters: {'badge_num_1': 'None', 'badge_type_1': 51352218}]

**Comment by kitsuta** [comment]
We found this was relegated to @jmdawson's dev instance. It's no longer an issue.
