### ISSUE TITLE
Staff cannot be panelists

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#162]
Because Staff and Panelists are both ribbons, a staff member cannot be a panelist in RAMS, and thus cannot be selected as running a panel.

How might we fix this? Multiple permitted ribbon types? Mod the panels plugin to be configurable about what ribbon types it admits?

(Opened on behalf of programming.)

Priority? Nice if we could sneak it in for 2017 soonish, but "no sooner than 2018" seems a distinct possibility.

**Comment by kitsuta** [comment]
Oh... we've already done multi-select ribbons in the main MAGFest code
base. It was a big enough refactor that I am... reluctant to port over
those changes manually. I might have to go through the pain of catching us
up.

**Comment by kitsuta** [comment]
Fixed by https://github.com/magfest/panels/commit/0659b2dfc370a902d65aea560b59eb38a1b5b11c.
