### ISSUE TITLE
As a dealer, I want to be able to add a Power option to my application

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#17]

**Comment by jmdawson** [comment]
When a dealer buys a table, they need to be able to specify Power as an add-on option. Power is only provided at the table upon request, and, going forward, is likely to have a non-zero dollar value attached to it. What additional information do you require?

**Comment by kitsuta** [comment]
I think I'm good -- I didn't anticipate needing extra info before implementing this, actually. I was planning on adding a checkbox to the dealer application that said how much power would cost and allowed dealers to add that to their app. Of course, eventually we'd want to know how much power costs.

I guess the only thing that'd change the implementation is if the price of Power changed based on some metric (date of application, number of tables).

**Comment by kitsuta** [comment]
Note: Make the Power field an integer field in case we want to charge for multiple power drops.

**Comment by kitsuta** [comment]
Fixed by the commit referenced above.
