### ISSUE TITLE
Admin>People>Attendees - No way to sort by registration datetime

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#175]
I have no way to view a list of attendees sorted by the datetime they registered. This would be helpful (especially for testing) if, for example, I know an attendee just registered and want to pull up their info.

**Comment by kitsuta** [comment]
It's not as elegant, but we actually have a list of registrations sorted by newest first. For staging, the url is: http://rams.test.furfest.org/rams/registration/recent
