### ISSUE TITLE
Question: Should all attendees in a multi-registration receive emails with full reg details?

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#178]
Question for Rama: Currently, if multiple attendees register as part of the same transaction, only the first attendee receives an email with full reg instructions (e.g. badge pickup location) and contact info for the reg team. Should this be the case? Compare:

---

You (First Reg) have preregistered for Midwest FurFest at the Attendee level and your payment of $55 has been received. 

Your registration confirmation number is c3b274f0-439d-4a89-89f3-ca53d6d7039f. You can update your contact information, change your badge name, or upgrade you registration level by clicking here. 

Badges are not mailed out before the event, so your badge will be available for pickup at registration when you arrive at Midwest FurFest. Simply bring a photo ID to registration, where you can pick up your badge. Location and hours of registration will be announced at a later date on our website and social media. Your registration may be cancelled and refunded until preregistration closes on Friday, November 17, 2017. Please email registration@furfest.org to request a cancellation and refund. 

If you have any other questions about your registration, please email us at registration@furfest.org. Thank you for again registering for Midwest FurFest and we’ll see you at the con. 

Midwest FurFest Regsitration Team
registration@furfest.org
http://furfest.org

---

You (Second Reg) have preregistered for Midwest FurFest at the Shiny Sponsor level and your payment of $275 has been received. 

Your registration confirmation number is 3608377e-1490-41c9-b50c-b6bc4dc7bc01. You can update your contact information, change your badge name, or upgrade you registration level by clicking here.

**Comment by ianlayton** [comment]
It would be helpful if this went to the email in the specific registration.

**Comment by kitsuta** [comment]
All registrants in a transaction get the exact same email. Our email system doesn't care about the transaction, so there's no difference to it whether your badge is bought on its own or with other badges.

It's highly likely that your email client is automatically hiding the extra text, which is the exact same in both emails. To see what the server sends, compare these two emails -- they were 'sent' on the staging server to two badges bought in the same transaction:
http://rams.test.furfest.org/rams/emails/sent?id=a1138f42-5290-496a-b17f-cec90a5174e5
http://rams.test.furfest.org/rams/emails/sent?id=84876ad7-f42e-482f-9255-850294597b64
