### ISSUE TITLE
As a dealer, I want to be able to add dealer assistants

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#18]
This may already be done in the system depending on exactly what is needed -- further evaluation is needed.

**Comment by jmdawson** [comment]
What sort of further evaluation do you want to see?

**Comment by kitsuta** [comment]
I just want to make sure that dealer assistants don't get special treatment, like a different ribbon type than regular dealers (e.g. the leader of a dealer group gets a "Dealer" ribbon and all other badges in that group get a "Dealer Asst" ribbon).

**Comment by kitsuta** [comment]
Per the email from the Dealer's Den head, 'dealer assistants' don't need special ribbons, so this does not require code changes.
