### ISSUE TITLE
"No Hacking Allowed"

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#188]
While in con mode, when attempting to enter a registration from the attendee side for any level, it's showing the "No Hacking Allowed" message again.

**Comment by ianlayton** [comment]
can I get an ETA on this fix because I'm unable to do further testing of the onsite functionality until I can enter at the door registrations as an attendee.

**Comment by kitsuta** [comment]
This was a bit tricky, but I've finally figured out that it's a problem with the HTML form sending in two badge types. Should have it fixed for staging today.

**Comment by ianlayton** [comment]
I'm wondering if this has been pushed yet. I can't check because the system appears to be down. Thanks.

**Comment by kitsuta** [comment]
Should be pushed to staging by now!

**Comment by ianlayton** [comment]
I'm not a hacker anymore...so that's good :)
