### ISSUE TITLE
Level titles and order for on site

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#189]
In "at con mode" on the attendee side, can we rename and reorder the levels to this:

Standard
Sponsor
Shiny Sponsor
Friday
Saturday
Sunday

Also, is it possible to hide the days that aren't available yet, like on Friday, only show Friday

**Comment by kitsuta** [comment]
It sounds like the behavior you want is to turn off presell_one_days. When `presell_one_days` is turned off, the option on the at-door menu will say "One Day" and the price will change at midnight according to the prices set for each day.

If we were to do this, would you still want the badges to say "Friday", etc on them? Or is "One Day" just fine?

**Comment by ianlayton** [comment]
I would like to keep them saying "Friday", "Saturday" and "Sunday" verses "One Day" on the badge if possible.
