### ISSUE TITLE
As a dealer, I want tables to be the correct prices

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#19]
How much work this involves depends on MFF's pricing structure for tables -- needs further evaluation

**Comment by jmdawson** [comment]
What info do you need? I'll forward that to Brendan so we can keep going on this.

**Comment by kitsuta** [comment]
I need to know the pricing structure for tables -- do they change? Is it a set price per number of tables (e.g., 1 table is $$, 2 tables are $$$)? I'd also need to know if dealers are able to apply for half-tables or if it's just whole numbers.

**Comment by jmdawson** [comment]
As I understand it, 1 table is a certain price, 2 are a different, three are a third, etc.  I don't know what those values are, as yet, nor do I know what the maximum number of allowed tables is.  I do not _believe_ there is any allowance for non-integer tables.  I do not believe there is any date-based pricing for tables, either.

**Comment by kitsuta** [comment]
OK, this shouldn't require any code changes then. We'll just need to know the actual prices so we can set up the correct config.

**Comment by jmdawson** [comment]
Tables have an arbitrary price structure (1 table is X, 2 tables is Y, 3 tables is Z, 4 tables is A, 10x10 Booth is B). Challenge: We don't allow more than 5 tables, but we DO allow a booth.  How do we handle the booth?

**Comment by kitsuta** [comment]
We'd set the booth as some arbitrary number in the code (like '10' for '10x10') and change the text it displays using the MFF plugin's config.py file. As long as you configure its price, it should work pretty transparently on the user side.

Doing that configuration is complex and to be honest, I'd have to look at what I did for AnthroCon back in the day to refresh my memory. Let's move this to the backlog so I can do that tomorrow. Just tell me what integer you'll use for the 10x10 booth and I'll handle the name change.

**Comment by jmdawson** [comment]
10 is fine

**Comment by kitsuta** [comment]
Fixed by https://github.com/MidwestFurryFandom/mff-rams-plugin/commit/add2dbe977426e2eac1839c2cfee06f55cd0c401.
