### ISSUE TITLE
Registration terminal changes

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#192]
On this page: http://rams.test.furfest.org/rams/registration/new

1. Can we get rid of the "Badge Remaining", it's not applicable for us.
2. We need to change the badge replacement fee to $20
3. When "charge" is selected for the "record a fee", can the page go to the arbitrary credit card charge page so it can easily be charged
4. Please remove mentions of Square in the payment dropdowns, charge form and the in "Click Here to create arbitrary credit card charges if Square"

**Comment by kitsuta** [comment]
I'm a little confused by point 4. Does MFF take payment from any provider besides Stripe? If not, how has MFF handled 'group' transactions in the past? People very frequently want to charge multiple badges in one go -- did the old system just handle this?

**Comment by ianlayton** [comment]
That is a good point, we always handled them as separate transactions. Let me talk to our finance people and see if we can do Stripe or possibly get a reader for Paypal, which we already have.

**Comment by kitsuta** [comment]
OK! The reason the 'square' payment is an option is because MAGFest also does at-door payments outside of Stripe (using, as implied, Square). Making the system be able to count multiple badges inside a single stripe transaction while at the con is doable, but not easy.

**Comment by ianlayton** [comment]
Actually...I have an idea...I can use the "arbitrary credit card charges" page to do batch purchase. That way we don't have have money going into multiple places and we don't need a special piece of equipment.

So for #4:

Can I get the line at top changed to: "Click Here to create arbitrary credit card charges or run a purchase"
And in the payment dropdown, remove Square and replace with Stripe Batch Payment

**Comment by ianlayton** [comment]
any update on these requests please.

**Comment by kitsuta** [comment]
I've altered the wording now, @jmdawson will need to add the following to config under `[enums]`:
```
[[payment_method]]
square = "Stripe Batch Payment"
```

**Comment by kitsuta** [comment]
Still working on changing how the 'record a fee' button works, which is a bit more involved than the other stuff listed.

**Comment by ianlayton** [comment]
Concerning the "record a fee" button, If it's something that will take a lot of time, it's probably not worth it at this point. It just seemed like a better work flow to me for MFF specifically, given we don't use the stand alone credit card terminals. It probably won't be use much, so it's not something that will give us a lot of bang for effort.

**Comment by kitsuta** [comment]
Oops, didn't see that comment :) It wasn't too painful, just required re-figuring out the workflow.
