### ISSUE TITLE
Payment for art show and registration didn't flag registration as paid correctly.

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#194]
Nicolas Alcala registered for art show and created a membership at that point. Because of the limits on the signup page, initially he purchased 4 panels and 1 table, but it was upped to 8 panels and 3 tables and the amount due was overridden to 55 for the art show space by art show. Alcala paid $110, $55 for the registration and $55 for the art show space, payment was logged correctly in the system and the art show purchase was flagged correctly. However, the registration part wasn't. Payment was 10/24 at 22:55

This *might* be an edge case due to the face that her art show amount due was manually set.

**Comment by ianlayton** [comment]
Another instance of the same issue:

Marissa Rasp submitted a payment for $65 for two artshow panels and a registration. Originally, the request was for four art show panels. The request was changed to two panels and approved. At a later time, the base price was changed from 20 to 10. Payment was made yesterday for $65. The art show panels were marked as paid, but the registration was not.

**Comment by kitsuta** [comment]
OK, reproduced this on my local server. The payment amount is being recorded, but literally their payment status is not changed. I'll have a fix for this in code shortly.
