### ISSUE TITLE
Badge numbering issues

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#196]
A few issues on this:

On the checkin screen, after marking someone as paid, when attempting to check someone in, getting the following error:

"Badge Number Required"

For attendee badges, a badge number is being shown on the attendees detail page
For daily badges, no badge number is being assigned, even after payment.

ALL badges (no matter their type) must have a badge number and they must be automatically assigned. they also shouldn't be able to be overwritten once assigned as easily as from the check in screen.

I thought this was working before, maybe a setting got changed somewhere?

**Comment by ianlayton** [comment]
Any update on this please.

**Comment by kitsuta** [comment]
Daily badges not getting numbers is a config change -- will interface with @jmdawson about that and work on getting rid of those input boxes.

**Comment by ianlayton** [comment]
This seems to be all good now, thank you.
