### ISSUE TITLE
Badge type prices are independent

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#2]

**Comment by kitsuta** [comment]
Question: What will badge type prices be doing? Will each type need to have price bumps (e.g., increase by $5 on a certain date?)? Will each type need special pricing at the door? This affects the scope of this issue.

**Comment by ianlayton** [comment]
There are four major badge types. Standard, Sponsor, Shiny and Daily.

Sponsor and Shiny are the same price, no matter when they are purchased.

Standard pricing changes based on when they purchased. Last year it was $45 from preregistered open until Sept 30, then $50 from Oct 1 to close of prereg, then $55 at the door.

Daily prices are based on the day they are purchased for. Last year it was $25 for Friday, $30 for Saturday and $25 for Sunday.

**Comment by kitsuta** [comment]
Awesome, this fits in pretty well with our current system. I'll just need to add the Sponsor and Shiny badge types and give them custom prices. Thank you!
