### ISSUE TITLE
power_price is in two places: why?

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#225]
Let's figure out what the one right place for power_price is. If it _has_ to be in two we should get that fixed in an iteration.

**Comment by kitsuta** [comment]
`power_prices` is an mff-rams-plugin config section. It should look like:
```
[power_prices]
1 = 40
```

You should be able to safely remove it from whatever other development.ini it's in.

**Comment by jmdawson** [comment]
So slight issue: the dealer page references the power_price variable, resulting in this:
<img width="216" alt="screen shot 2018-06-01 at 15 01 53" src="https://user-images.githubusercontent.com/910490/40860980-e99fb20e-65ac-11e8-9f6a-acfd72197450.png">

We need to update that posthaste.

**Comment by jmdawson** [comment]
That said, it's also working as it should where it really matters, so nobody is really getting surprised:
<img width="288" alt="screen shot 2018-06-01 at 15 04 55" src="https://user-images.githubusercontent.com/910490/40861038-37b0516a-65ad-11e8-8d8f-85c5bf8db3f4.png">

**Comment by kitsuta** [comment]
Oh shoot, I see now. With jinja2 we should be able to just refer to
power_prices[1]. I'll have to try that

**Comment by jmdawson** [comment]
turns out groupextra.html referenced `c.POWER_PRICE`! Oops. It now references `c.POWER_PRICES[1]`. Much better.
