### ISSUE TITLE
IL Business Tax Number entry lost when form reloads after error

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#234]
After submitting an application with any invalid field resulting in an error, the page refreshes to allow the user to fix their mistake. However, in doing so, any information entered in the Illinois Business Tax Number field is lost.

This seems to be the only such field affected, likely because it is a new addition. Because it is an optional field, this can easily lead to a user thinking they provided this information, not realizing it was lost after an error.

**Comment by kitsuta** [comment]
Is this on the dealer application or the dealer group confirmation page?

If the former, this may be a symptom of the more serious issue of the field not saving at all.
