### ISSUE TITLE
No verification done on IL Business Tax Number field

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#235]
No verification is being done on the )optional) IL Business Tax ID field. While I don't currently have information on valid ID formats to do proper regex verification against, this lack of verification also allows submission of emoji characters (no other field allows this).

**Comment by jmdawson** [comment]
So this guy.... https://www.linkedin.com/pulse/ibt-number-how-find-your-idor-business-tax-chris-amundson

Says it's an 8-digit number "usually" hyphenated in the middle.

**Comment by kitsuta** [comment]
Do we also want this field to be non-optional?
