### ISSUE TITLE
Downgrading badge selection from (Shiny) Sponsor to basic Attending does not hide shirt size field

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#239]
Selecting Sponsor or Super Sponsor as a badge level reveals the Shirt Size dropdown, as it should. Re-selecting the basic Attending badge level, however, does not hide this dropdown once revealed. The dropdown should be hidden, and probably any data stored in the field purged, when a badge selection is downgraded like this.

**Comment by jmdawson** [comment]
Fixed by #230 (which is now deployed on staging)
