### ISSUE TITLE
CRITICAL: Downgrading from (Shiny) Sponsor to Attending badge level does not correctly update badge pricing

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#241]
A critical addendum to #239 worthy of it's own bug report. During the registration process, if a user selects (Shiny) Sponsor and then selects the basic Attending level, not only does the shirt size stay (as reported in the linked bug), but when reaching the payment step the user is still being charged the (Shiny) Sponsor price.

**Comment by SkylerRingtail** [comment]
Note that this issue does NOT occur when downgrading from Shiny Sponsor to just Sponsor; only from one of those two to Attending. Additionally, going from Shiny to Sponsor to Attending will charge the Sponsor price, not Shiny (the price being charge is the previously selected level.)

Just selecting Attending without selecting anything else first works as expected.

**Comment by jmdawson** [comment]
fixed by #230
