### ISSUE TITLE
Should we add "Written works" as a dealer merchandise option?

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#243]
Our current categories cover most of the common things I see sold at conventions, but one big omission that could potentially offend/ostracize some dealers is the lack of an explicit option for books, comics, and other written works. Yes, they could select Other, but I think this is one category common enough in the fandom to merit its own selection. Note that comics might be classified under Visual Art, so perhaps this option would be best named as a general "Written works."

Two other less common categories include Music and Gear (e.g. cosplay or leather gear), but these can more reasonably be handled by the Other category.

**Comment by jmdawson** [comment]
Dealers staff are supposed to provide a list of what they want in those fields. It's a config option we can handle.

**Comment by jmdawson** [comment]
Got a list from dealers. Added written works as a pre-emptive thing. Will see if he gets back to me w/ a yes/no on it. Makes perfect sense, though.

**Comment by jmdawson** [comment]
Approved by Brendan. Also added "Plush products" as well.
