### ISSUE TITLE
"This person isn't coming" button missing on dealer application update form

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#244]
The instructions for a multi-dealer dealer application mention a "This person isn't coming" button to unset a badge. This button is not visible. Note that the application in question is "Pending Approval," which may have something to do with it. If so, the instructions should be updated to reflect this, e.g. "**If your application has been approved** and a planned Dealer Assistant cannot attend..." (emphasis added to highlight difference).

**Comment by SkylerRingtail** [comment]
Update: Even after approving the group and paying for the badge, this option is not available.

**Comment by jmdawson** [comment]
Does not _need_ to be fixed to launch, but we should fix it soon.
