### ISSUE TITLE
Minor grammar update for multi-dealer application instructions

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#245]
On the page for updating an existing dealer application, we have instructions for handling applications that include Dealer Assistants. Part of this text reads as follows:

"Please assign these badges between now (using the links below) and the close of preregistration; any badges unclaimed at that time will be invalid."

This would be better phrased as:

"Please assign these badges (using the links below) before the close of preregistration; any badges unclaimed at that time will be invalid."

Note the change of position of the parenthetical text, and the removal of the extraneous "between now and" (of course any time before pre-reg is going to be "between now" and then; it just sounds silly).

**Comment by jmdawson** [comment]
Changed to this: "Using the links below, please assign these badges before the close of preregistration; any badges unclaimed at that time will be invalid."
