### ISSUE TITLE
Importing events causes 500 error

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#275]
```
ESC[36mweb_1            |ESC[0m 2018-09-25T15:51:53.115747940Z       File "/app/plugins/uber/uber/site_sections/import.p
y", line 104, in import_model^^
ESC[36mweb_1            |ESC[0m 2018-09-25T15:51:53.115751625Z         setattr(model_instance, colname, val)^^
ESC[36mweb_1            |ESC[0m 2018-09-25T15:51:53.115755186Z     UnboundLocalError: local variable 'model_instance' re
ferenced before assignment
```

**Comment by kitsuta** [comment]
Note: this error doesn't occur for ANY event imports, just for a specific file we both have. So it's not clear yet if there's a bug in the system or if something unexpected in the file itself is the issue.

**Comment by jmdawson** [comment]
True, it would be better to formulate a 'clean' file and see if that does the same thing.

**Comment by jmdawson** [comment]
Managed to sort this out w/out making any changes, just massaging the input data until all of the weirdly-encoded characters were expunged.
