### ISSUE TITLE
As an attendee with an application, I want to view my application and its status via my confirmation link

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#29]
Right now, dealers can only view their group members' names on the confirmation link they get in their confirmation email. We should change this page to include the application information (e.g., the extra info we collect for dealer groups), plus the application status.

Dealers should also be able to edit this information.

**Comment by kitsuta** [comment]
A few questions here:
1. Is there any information on the app the dealer _shouldn't_ be able to edit? Specifically, should the dealer definitely be able to edit the number of tables and badges they have requested?
2. Currently, the group badge claiming workflow redirects attendees to the 'group management' page when they claim a badge. If we add the ability to edit application info onto the group management page, we open up this editing ability to _anyone who claims a group's badge_. Therefore, do we want to prevent attendees from being redirected to this page, effectively restricting access to only those who have the group management page's URL specifically?

**Comment by jmdawson** [comment]
1. Let's start with number of tables & badges as non-editable for now
2. Yes, we want to stop that redirect, and instead send them to confirmation of their own reg (with indication that they are associated w/ the group)
3. Default to non-editable, but don't preclude changing that decision later
