### ISSUE TITLE
As an approved Dealer, I want to be able to purchase tables as long as I purchase at least one badge

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#30]

**Comment by kitsuta** [comment]
Do we want dealers to be able to add tables to their group after they have been approved? Should there be any kind of approval process for additional tables, or should it be entirely self-service?

**Comment by jmdawson** [comment]
Let's go with: No, dealers cannot purchase more tables after they've been approved. As long as admins can adjust the number of tables and price-to-pay after the fact, and send the dealer something to let them pay more, we should be ok.

**Comment by kitsuta** [comment]
Sounds good!
