### ISSUE TITLE
As a Registration staffer, we need to cut down on the amount of network used by the onsite registration system, so it can be more responsive when registering attendees.

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#303]
Find a way to cut down on the amount of network used by onsite registration system. Ideas include: having a local application server that uses offsite database.

Might want to also look into caching here or if there are any performance problems with RAMS itself that might be contributing.

This issue might be related: #155

**Comment by kitsuta** [comment]
I would guess at some point we'll want/need data on exactly which containers were using network, how much was being used, whether it was traffic between containers or between at-con computers and the server, and what that traffic was like compared to the traffic used during the (presumably fairly intense) traffic when pre-reg opens.

Sideboard, the framework that RAMS uses, has a [profiler](https://github.com/magfest/sideboard/blob/a289586acd28476b00a301cdc77a778b2325c95c/sideboard/configspec.ini#L91) based on CherryPy's profiler that can also give us some information if we turn it on (for staging, of course). After Rob Ruana coded it up he used it to optimize a lot of the system... that was a while back, though. I wonder if something happened after that increased network usage, or if MAGFest just never cared about that much.

**Comment by DarkKilauea** [comment]
Marking this with "Needs more information" since we need to do a review of the network usage RAMS currently has before we can figure out what needs to be adjusted.

**Comment by jmdawson** [comment]
@kitsuta I think we accomplished this w/ Adam's help

**Comment by kitsuta** [comment]
We did, thank goodness! The root problem ended up being the at-door reg page polling the database multiple times for the same information, so we cached that variable.
