### ISSUE TITLE
Create a module for the new Marketplace department

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#307]
Key Features      
* Register early, similarly to how they register for Dealer’s Den      
* separate badge pickups for Marketplace participants (this is really more   of a reg process item)      
* application process & waitlist similar to the dealer’s den and/or art show     
  * Starts after Dealer’s Den Waitlist announced (this would be configurable, relationship probably manual)      
  * App needs something like a Business or Artist name, separate from Badge name      
  * App otherwise needs all reg data (recommend tie to reg similar to Dealer’s Den Apps)     
  * Ability to convert a Dealer’s Den Application into a Marketplace Application, for folks who didn’t get in to DD. Rate as should-have, not must-have.      
  * Must handle payment for Marketplace application & reg (basically, more of the same stripe integration)

Crimson Notes: My read on it? We’d set it up as its own module in RAMS, very similar to the Art Show. With luck, after the art show work, it would not be too hard to copy enough of the Dealer’s Den Functionality into said new module to do what   we want. Dates should be configurable like all the other module dates. I expect many of the same automated emails we send out for other modules.

**Comment by kitsuta** [comment]
Would marketplace applicants also need to manage their own groups (e.g., would they be able to have assistants)? Or would it be more like art show, where each marketplace application is tied to a single person?

**Comment by ianlayton** [comment]
Market place is only a single person. It's basically a souped up artist alley spot.

**Comment by kitsuta** [comment]
Awesome, that's a considerably simpler implementation!

**Comment by kitsuta** [comment]
I've gone as far as I can with this for right now. There's a lot of implementation/workflow details I need, so I sent an email to Kelshin with the following questions:
- Is business name really all the marketplace app needs? Dealer applications ask for a website URL, a description of what the attendee plans to sell, a selection of possible categories for their wares, an Illinois Tax ID, a business address, and a description of their special needs, if any. Which of these would also need to be on a marketplace application?
- Art show applications allow people to create a new badge or apply using an existing confirmation number, while dealer applications always create a new badge that cannot be checked in or paid for until the application has been approved. Which of these approaches would you prefer, or did you have something else in mind?
- Do you know yet what the cost structure for a marketplace application will be? Can the attendee apply for multiple tables, or is it a flat fee? Are there any extra perks they can pay for, like how you can pay to have power at your dealer table?
- Do you know yet what the dates for marketplace applications should be? Both art show and dealer applications have an open date, an auto-waitlist date, a close date, and a payment deadline.
- The issue mentions converting a Dealer application into a Marketplace application. Should that be automatic, or should the attendee initiate that from their dealer application?
