### ISSUE TITLE
Break away payment of registration from dealers room and art show table requests

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#308]
Investigate a way to break payment of registration (and art show tables) from dealer room   requests so dealers on the waiting list can finish purchasing their registration without being removed from waiting list.

**Comment by Hugmonster** [comment]
I think this would be good, but this year it seems that Art Show is starting really slow and I do not have anything tied up currently.

**Comment by kitsuta** [comment]
Estimate: 10 hours to overhaul RAMS to use itemized payments instead of stapling almost everything to someone's badge cost.

**Comment by fursuit69** [comment]
I think it's a good idea. Also opens up future flexibility for expansions,
like con merch or other department items..

**Comment by kitsuta** [comment]
The bulk of this is now complete!
