### ISSUE TITLE
Setup RAMS so it can be ran locally during the event on short notice

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#309]
Reduce sensitivity to connectivity issues by having some way for RAMS to switch from being run remotely to being run locally during the event on short notice.

This may be related to #303 

Since the underlying cause seems to be the same, solving the performance issues of RAMS during registration might render this ticket obsolete.

**Comment by jmdawson** [comment]
Performance issues were pretty much resolved in 2019. Let's call this moot for now.
