### ISSUE TITLE
As an approved Dealer, I want to be able to purchase additional badges at any time

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#31]

**Comment by kitsuta** [comment]
Currently, dealer badges are a set "dealer price" different from the attendee badge price. I believe @jmdawson indicated that this is not the case for MFF, and that membership prices for dealers work the same as for anyone else. Is this definitely the case?

Additionally, are there any restrictions at all on the badge/table ratio, or on how many badges a dealer may add on to their group?

**Comment by ianlayton** [comment]
There is no difference in the prices for badges for dealers then attendees. Also, there is no limit on the number of "helpers" they have.

**Comment by kitsuta** [comment]
Fixed by the commit referenced above.
