### ISSUE TITLE
As a dealer staffer, I'd like to limit the number of memberships associated with a dealer application, to prevent misuse of the application process

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#313]
Is there any way to have a limit on the number of memberships that can be associated with a dealer application? 

Ideally, this would apply not only to the number of memberships requested on the application, but also to any that might be added afterwards. If possible, I'd like it to be three memberships per table requested, with a booth limit of 12. The reason for this is that last year I had at least one dealer who had a single table but listed twelve helpers; when asked about this at the con they admitted that it was done so a bunch of their friends wouldn't have to stand in line at Registration.  I'd like to avoid this happening again. If it's not possible or too complicated, I can probably enforce it on an individual basis. I'd like this implemented before we go live.

**Comment by kitsuta** [comment]
This is already enabled in code. `max_dealers` just needs to be set to 0 (it functions partly like a feature flag).

**Comment by jmdawson** [comment]
As soon as Brendan verifies it's working as he expects, we'll close this.
