### ISSUE TITLE
As the Fursuiting Track Lead, I'd like attendees to indicate if the plan on bringing a fursuit, so I can better plan resources for them

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#316]
Corvus from the fursuiting track has requested a checkbox or some other feature during registration to ask attendees if they're planning on fursuiting or bringing a fursuit. Their reasoning is that with a better count of suiters they'd be able to better staff the lounges with supplies and have more   fursuit tags on hand.  Again, no language exists, but however it gets crafted, it should probably include something about not being a commitment to suit or not to suit and that we're just looking to offer a better con experience.

**Comment by kitsuta** [comment]
You can have folks look at https://github.com/MidwestFurryFandom/mff-rams-plugin/pull/152 to see the current wording and UI and give feedback!

**Comment by ianlayton** [comment]
Registration is fine with wording in the link above.

**Comment by jmdawson** [comment]
Done.
