### ISSUE TITLE
As an approved Dealer, I want to be able to purchase badges without purchasing tables

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#32]

**Comment by kitsuta** [comment]
Clarification needed: does this user story refer just to adding badges, or does it mean:
1. That a dealer should be able to have badges but no tables, period?
2. That a dealer should be able to pay for their badges after being approved, and then pay for tables later?
3. Something else?

**Comment by jmdawson** [comment]
How does the system respond if a dealer registers, but is not approved? Will they still be able to buy an attendee badge w/ the info they entered?

**Comment by kitsuta** [comment]
When outright declining dealers, admins can opt to send them an email with an attendee badge (the badge is the price badges were when the dealer first applied). Otherwise, dealers can just put their information into the pre-reg form to buy a badge -- it warns them that they have an application but lets them continue if they want.

**Comment by jmdawson** [comment]
Brendan has been informed of the waitlisting procedures, and the reject-and-convert-badges button and accepts this. I move that this issue be closed.
