### ISSUE TITLE
Incorrect required fields in dealer app

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#320]
In the dealer room application, business mailing address and personal mailing address isn't marked as required and isn't being flagged as being required. These fields are required for us.

(note: tax number is not required)

![image](https://user-images.githubusercontent.com/11669617/61382384-4f332200-a872-11e9-8d87-2d4aa619ae21.png)

![image](https://user-images.githubusercontent.com/11669617/61382420-5f4b0180-a872-11e9-9878-579dd60c82be.png)

**Comment by kitsuta** [comment]
Per conversation with Eli (scrum master) and Debra (project manager), this and any other bug introduced by Promo Code Groups (attendee groups that MFF will not use) will be billed to MAGFest.
