### ISSUE TITLE
Stripe Payment Descriptions

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#327]
Description isn't being sent with the Stripe payment for registration payments. It should be the name of the people who the badges are being purchased for

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/11669617/61419065-410cf200-a8c2-11e9-8528-bb553e3ee6e7.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/11669617/61419089-52ee9500-a8c2-11e9-89e0-95af4cffb23d.png">

**Comment by kitsuta** [comment]
This bug was also introduced when adding promo-code groups, so it will be billed to MAGFest.
