### ISSUE TITLE
Unable to create placeholder badges in admin

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#335]
When attempting to make a place holder badge for a rollover or comp in admin and selecting “the attendee needs to register themself”, it still is requiring fields in addition to name, email address and payment. Specifically, it should allow the mailing address, badge name, phone numbers to be empty.

This may be due to the change earlier where those fields were mistakenly not required on the signup page.

**Comment by kitsuta** [comment]
Whoops, yes, those are related!

It looks like this is just clientside validation, which means you can actually get around it if need be by using your browser's developer tools to removed `required="required"` from the affected fields in the page's source code before submitting the form. Obviously that's a huge pain -- I'll need to update the JavaScript surrounding placeholder badges to fix it.

I didn't notice it requiring the badge name or phone number, only the address fields.

**Comment by ianlayton** [comment]
It's possible it's not requiring those fields...I just mentioned them as not needed

**Comment by ianlayton** [comment]
So we have about 100 comped badges we need to add to the system. I basically told reg the trick if someone gets antsy on us, but if we could get the fix in place this weekend, if possible, that would be great :)

**Comment by jmdawson** [comment]
Can this not wait until we add the features that let us add staff through the API? It’s not like they won’t get their badges in time.

**Comment by ianlayton** [comment]
It will be needed for any hotel room lottery.

**Comment by jmdawson** [comment]
And there has been no project planning done for this work, nor any contract addenda drawn up, so the odds anything can be done this weekend are near zero. 

- Crimson

**Comment by ianlayton** [comment]
Please let me know a time frame this can be dealt with then. Please take in consideration that this is a bug that was introduced by another bug fix. Also, please take in consideration this fix is needed sooner then later because of the reasons listed above.
