### ISSUE TITLE
As an admin, I want to know how to change dealers' tables before approving them

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#34]

**Comment by kitsuta** [comment]
Clarification needed: Is this separate from the admin being able to change the application? That is, do we need both "number of tables this dealer _can_ purchase" and "number of tables this dealer _has_ purchased" as fields? Does this also imply allowing admins to approve dealers for _fewer_ tables than they requested, and if so, do we want a way to detect that and let approved dealers be able to confirm that, or do we just want admins to reduce the number of tables on the dealer's app?

**Comment by jmdawson** [comment]
Let's work up a document for dealer admins on how to correctly adjust number of tables and price on an application before approving the dealer so they can pay.

**Comment by jmdawson** [comment]
Draft document looks good.  Dealers material looks comprehensive, so I consider this done (though we probably need to revise a bit).
