### ISSUE TITLE
"Do you plan to fursuit?" buttons very difficult to visually distinguish

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#341]
From #316. The Yes/No buttons are extremely difficult to visually distinguish. At a glance, I can't tell which option is selected. These buttons need more visual distinction, or should just be remade as simple radio buttons with Yes / No (default) options. The green/red color really makes these buttons stand out in a way I'm unsure is necessary, so I'm inclined towards radio buttons.

![image](https://user-images.githubusercontent.com/28108495/62994536-0c894900-be22-11e9-834b-ee743c7e0749.png)

**Comment by SkylerRingtail** [comment]
The admin side Attendee Data view shows a different button style (also on a different part of the page - the bottom) than other views. This one is easier to distinguish (though could still be difficult for users with visual impairments).

![image](https://user-images.githubusercontent.com/28108495/62994972-38a5c980-be24-11e9-829a-7c25c07a718c.png)

**Comment by jmdawson** [comment]
I concur on the usability issues, but the relevant stakeholders approved the current implementation. We can revisit the UX for the 2020 cycle, because I agree it's bad like it is.
