### ISSUE TITLE
As head of Dealer's Den, I want to be emailed whenever an approved dealer makes a payment

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#35]

**Comment by kitsuta** [comment]
Question: Does this include:
1. Dealers adding badges on their own?
2. Dealers paying for extra tables?

Or is it just about the initial payment of an approved app?

Relatedly, do we want to instead or additionally create a report of _unpaid_ dealers?

**Comment by jmdawson** [comment]
By default, let's email the designee (designees) any time a dealer engages in a transaction that requires money.
