### ISSUE TITLE
Move art_show and badge_printing plugins into this repo.

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#370]
Suggested by Vicki.

**Comment by jmdawson** [comment]
Seconded

**Comment by jmdawson** [comment]
Should MFF_rams_plugin also get included?

**Comment by kitsuta** [comment]
We'll probably want to split a few things out from it, like the comped badge report, but most of those should still be separate. We just found that there's no real reason to keep the "feature" plugins separate because if you don't want them you just don't use them.

**Comment by jmdawson** [comment]
@kitsuta I think we have completed this, yes?

**Comment by kitsuta** [comment]
Yup!
