### ISSUE TITLE
AZTECH codes being sent to profiles with incomplete registration

### ISSUE THREAD

**Issue by adebus** [MidwestFurryFandom/rams#372]
In sending out the "Check in faster at Midwest FurFest" emails today, many emails went to attendees who have not completed registration (I.E. in the "New" state). This includes dealers who are waitlisted, as well as people who started to register and then, for whatever reason, did not complete it. Additionally, the email was sent to attendees tagged as "Staff".

This has caused approximately 30-40 tickets so far in the last 5 hours with people who were told they weren't vending at the convention, people who decided they weren't attending, and staff members (both tickets, and lots of chatter in staff channels), asking why they received these 2D barcodes.

It would be helpful for the 2020 convention to either not send to anyone except those with paid and completed registrations, or to be able to select the profile of people we want to send the email to.

**Comment by kitsuta** [comment]
What you mean by people who started registering and then stopped? The system doesn't physically create a registration if someone doesn't finish preregistering.

Code task here would be to override the email definition in mff-rams-plugin to only send to Completed badges that are not Staff. We should also just set any waitlisted dealers to "Pending" status (new to MAGFest as of 2019) since they shouldn't get _any_ emails.

**Comment by adebus** [comment]
I might have misunderstood one of the tickets that came in. I have just been scanning much of Jira, rather than investigating every ticket.

I do know that the vast majority of tickets we've gotten have been related to waitlisted dealers, some of whom are VERY upset about this email. One threatened potential legal action if it meant that we had charged her card (we hadn't, but...yeah)

**Comment by kitsuta** [comment]
Oof, that sucks. Emails going out to the wrong people is always basically the worst, sorry the system behaved unexpectedly. Hopefully the pending status will cut down on waitlisted dealers being contacted unnecessarily. Actually, pending approval dealers should get the same treatment, just in case.

**Comment by adebus** [comment]
This is an example of a Waitlisted Dealer who got the email:
![image](https://user-images.githubusercontent.com/4514884/70013789-98d48e80-152d-11ea-8d19-86a534b2ee19.png)

As you can see, they're in a New state, as opposed to Complete, so I think your proposed solution of only sending to Complete, Non-Staff registration profiles should eliminate most of the unexpected emails.

**Comment by kitsuta** [comment]
I have, quite some time later, realized that the reason MAGFest has never run into this problem before is because any unapproved Dealers are explicitly deleted well before this email goes out. That makes fixing this way easier since it's not a bug, just an oversight in the code.
