### ISSUE TITLE
As a dealer admin, I may want to comp tables for dealers

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#38]
Currently, the system doesn't support this well natively -- dealer admins can manually set a dealer's total price, but this will not interface well with self-service additional badge purchases. Needs more details on how important this is and how we might want to solve it.

**Comment by jmdawson** [comment]
That may be acceptable.

**Comment by jmdawson** [comment]
Let's just call this done.  We'll work up a procedure for handling this.

Basically, have the dealer apply for what they want, then Brendan can handle the relatively small number of comped tables through careful math.

**Comment by jmdawson** [comment]
Going to icebox this as well. It'd be cool to make this more user friendly, but not in 2017

**Comment by jmdawson** [comment]
Closed as stale but we can reopen if we need it.
