### ISSUE TITLE
As an attendee, I want to be able to create an account during my registration so that I can securely manage my reg later.

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#385]
> Maybe we style the link to the prereg page as a “Create new account” link to encourage people to sign into their account and buy badges through their account management page

> OK so basic plan is to include an account email and password field(s) on the index page, then set up the account etc when the attendee pays for the badges. Confirmation link for the account goes to account management page — if an account only has one badge under it, that redirects to the badge page and the account details can be changed on the badge page. Otherwise the account management page has a list of links and apps that it manages
> 
> Beyond that I’ll need to figure out how the confirmation emails should work, add tools for admin accounts to reset attendee accounts, add a way for attendees to bequeath new accounts to badges they’ve bought, and figure out how to integrate dealer applications since their workflow is different from prereg badges
> 
> I’ll also want to hook up a way to buy new badges under an existing account, which is probably going to be related to integrating dealer apps with accounts

**Comment by jmdawson** [comment]
Reg confirms this includes dealer, art show, marketplace apps

**Comment by jmdawson** [comment]
Re: multiple accounts managing one badge: reg prefers no.

**Comment by jmdawson** [comment]
Reg confirms it's ok not to require a confirmation email before completing the registration. So far that is a small enough number that they are comfortable fixing it as an admin activity.

**Comment by jmdawson** [comment]
When I click on "create new account" it takes me to the reg form w/ a username/password prompt at the top which says under it "log in" but if I enter credentials there, it says "no account exists." That's true enough, but it's a weird thing to see when you clicked "create new"

**Comment by kitsuta** [comment]
Oh yea, good point. We should probably rename the button to just "Register"
