### ISSUE TITLE
Typo: email_admin -> Midwest FurFest Registration -> "Midwest FurFest registration confirmed" template

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#395]
The signature line of the "Midwest FurFest registration confirmed" email template has a typo:

Midwest FurFest **Regsitration** Team
registration@furfest.org
http://furfest.org

**Comment by kitsuta** [comment]
Just a heads-up, this email signature is a config setting, so it will have the same typo everywhere until we update config.

**Comment by jmdawson** [comment]
Yeah that's fine, I requested tickets for emails, easier for me to keep track.

**Comment by fursuit69** [comment]
Good to know! I wondered if that was the case after I created the tickets. :) At least for the signature.

**Comment by jmdawson** [comment]
That should have been fixed a while ago, but I will make sure emails container is properly kicked.

**Comment by jmdawson** [comment]
Email sigs should be good to go, but you'll need to generate some new ones to be sure. The old previews are probably fixed as they were.

**Comment by fursuit69** [comment]
Notably on this one, I don't see the code for the sig in the "Here's what the template looks like though:" display for the template. 

A different reg email template preview has this: {{ c.REGDESK_EMAIL_SIGNATURE }}

But this template just has: Midwest FurFest **Regsitration** Team
registration@furfest.org
http://furfest.org

**Comment by jmdawson** [comment]
you will see an actual "compiled" email when emails have been approved and sent. You will see the template text when no such email has yet been sent.

**Comment by fursuit69** [comment]
Right. I mean that this and #394 may not have the reg email signature built into them. It may be straight text. I see other example emails that I think do have it built in.

If they do have the signature built in, then cool beans. :)

**Comment by kitsuta** [comment]
Ah yes, there is actually one instance of "Regsitration" being hard-coded (it's in the "mff-rams-plugin" codebase, not this one), good catch!

**Comment by kitsuta** [comment]
Just to follow-up, while digging into the typos further I realized that the "payment received" and "registration confirmed" emails use the same base template, and the typo in the signature was ONLY in that template. So, no change to config is needed after all, and https://github.com/MidwestFurryFandom/mff-rams-plugin/commit/3e19e34a70f45c4b9d820c91802019192e369af9 will fix the signatures in both emails.
