### ISSUE TITLE
Password Complexity for Attendee Accounts

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#396]
-Created single attending registration (Badge: Test 1 - RAMS Account Creation) 
-input new password "123" and paid via test stripe credit card.
-password was accepted

Request: Require standard complexity rules for passwords: 8+ characters - at least one capital, one number, and 1 symbol.

**Comment by jmdawson** [comment]
Good timing, those will be added in a very soon release.

**Comment by fursuit69** [comment]
Great!
