### ISSUE TITLE
Button Text Update: "Add Another Registration"

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#397]
I found confusing the "Add Another Registration" button on the "Registration Complete" screen after payment is submitted/account is created.

I initially interpreted it as "add another registration to the account I just made" and then discovered that it creates an entirely new registration/new account. This is fine!

But the button text could read "Create New Registration" or something clearer.

Screenshot of the affected page attached.
![Test3b](https://user-images.githubusercontent.com/90427815/132792431-84ecfb27-ecc0-426b-9634-7fc296d91ac9.png)

**Comment by kitsuta** [comment]
Ooh, great catch -- I completely forgot about this button.

**Comment by kitsuta** [comment]
We now support logged-in accounts during preregistration, and you're logged in immediately after preregistering, so now you ARE actually adding another registration to the same account.

**Comment by fursuit69** [comment]
That works too!
