### ISSUE TITLE
Minor Registrations - Price Corrections, Display Text Update

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#398]
I punched in test cases for minor badges. In the past we have not allowed these online, however given that we're allowing group registrations, we definitely should now.

However, prices are incorrect for two cases in the test server and may need to be updated for live production:

For attendees age 7-12: Price should be 1/2 regular attending membership.
For attendees 6 and under: Price should be free. Currently this is set for < 6 instead of <= 6. 

Display Text for attendees 6 and under should read: Attendees who are 6 and under get in for free!

See attachment for clarification. 

HOWEVER given that it is likely that we will not be allowing anyone < 12 into the event (due to not being able to be vaccinated, as of current guidance), this may be a moot point.  We should be prepared to have a flag/warning that displays in production saying that "Anyone under the age of 12 is not able to attend FurFest 2021 due to COVID-19 vaccination status." or similar.

That of course may change at any time...... 
![Test5](https://user-images.githubusercontent.com/90427815/132794896-df61bf53-3c3e-48ab-b690-1686a24ed65f.png)

**Comment by kitsuta** [comment]
The following config added to development.ini should take care of all of these changes:
```[age_groups]
[[under_6]]
desc            = "6 and under"
max_age         = 6
discount        = 999
can_register    = False

[[under_13]]
desc            = "Between 7 and 12"
min_age         = 7
max_age         = 11
discount        = 30
can_register    = False

[[under_18]]
desc            = "Between 12 and 18"
min_age         = 12```

We can remove the "can_register = False" from any age category down the road and the system will start letting attendees of that age register. As long as no one in the system is assigned to it, we can also change any other variables in an age category (min_age, max_age, etc) without issue.

**Comment by jmdawson** [comment]
Added to staging, @fursuit69
