### ISSUE TITLE
Update confirmation emails to accommodate attendee accounts

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#399]
“As it stands, if someone (A) buys a badge for someone else (B) along with their own, we will send B a link for a page that they won’t be able to log in to see”

Tauvix  2 hours ago
I think with the time we have, I think it's a reasonable assumption to say that "person A is buying multiple badges, they have access to all the PII, as they are paying for it, and there is no expectation that person B can access their registration at all. If they need to make any changes, they have to work through the person who bought the reg, person A"
That is not an uncommon workflow for anyone, including Ticketmaster

Blithe  2 hours ago
I'm perfectly fine with that.

**Comment by kitsuta** [comment]
I think a chunk of info got lost in translation, so just to confirm, that means that we should _only_ send a single confirmation email per account, and send it to the email address the account was made under during registration? If so, what email should they get (if any) if they add badges to an existing account?

Here's the other options:
1. Send a confirmation email to the account address, then separate confirmation emails for each attendee that does not link to their badge but prints the badge information
2. Send regular confirmation emails that print the badge information and include a note on which email their registration’s controlling account has

**Comment by kitsuta** [comment]
Follow-up question: what should the confirmation emails say about picking up your badge? Is that to be handled by the person with the account, or the individual with the badge?

**Comment by fursuit69** [comment]
I think a combination of 1 and 2 would be desirable:  Send confirmation to the account holder, then separate emails to each attendee that gives them their badge info AND note the email for the controlling account. 

For follow-up question:  Badges should be picked up by the registered person (as we will need to see ID). The main account holder cannot pick up other adult badges on their account.  So: Handled by the individual with the badge.
