### ISSUE TITLE
A dealer admin can assign a table to a dealer

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#40]

**Comment by kitsuta** [comment]
We'll need to know how this assignment should work. I know we discussed it a bit, but should it be a text input box? A choice from a list of choices?

**Comment by kitsuta** [comment]
Per Dealer's Den head, the table assignment field should be a 'text-only' field.

**Comment by kitsuta** [comment]
Fixed by the commit referenced above.
