### ISSUE TITLE
Attendee Login from RAMS Landing Page Results in 500 internal server error

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#403]
Testcase is ID 616b8723-2b0b-479b-8165-cc12700cffe5

After creating the attending badge and clicking the "here" text link to return to my account/badge info, I am directed back to the main RAMS landing page. 

Attempting to login to my account from the main landing page results in a 500 internal server error.

After attempting to login, if I click the "create new account" button, it will then go to the attendee pre-registration form with the account already logged in.

Logging out and attempting to log back in on the main landing page does not change that behavior. 

Screenshot added.
![Test10](https://user-images.githubusercontent.com/90427815/133015222-0bd49741-a393-4ef2-9696-f15da95fe9d0.png)

**Comment by kitsuta** [comment]
Yes, please show a screenshot of the 500 error if you have it!

**Comment by fursuit69** [comment]
Screenshot added to original post.
