### ISSUE TITLE
Dealer Assistant Badges: Unable to edit/modify assistant badges after purchase via Dealer Group

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#407]
After adding additional badges to a paid dealer group and then submitting assistant info for the secondary badge applications, the dealer is unable to edit/view/modify that badge directly. 

Since only the master account holder (the dealer) can add that badge via their account login, the master account holder needs to be able to edit/view/upgrade/modify the badge. 

The current workaround is to click the "This person isn't coming" button to scrap the completed assistant badge, and then add a new one via the "register someone for this badge" link.

Recommended Solution:  Have the link active that goes to the assistant badges, ie a link to "Example Dealer 2" in the screenshot. This would be similar to how the links for the Master Badge Holder (the dealer) operate.

Screenshots attached
![Member Management Final-Box](https://user-images.githubusercontent.com/90427815/133346812-f037e7c0-abcc-4926-9ffe-3424d56321a9.png)

**Comment by kitsuta** [comment]
In the interests of time I'll lock down group badges to only the group leader and re-enable the link, but we should at some point decide if we want to give them more flexibility to, e.g., send the 'Register someone for this badge' link to people in their group and have them manage their own badge/account.

**Comment by fursuit69** [comment]
Sounds good for now! That reflects the procedure I already wrote in a visual quick-guide I gave Dealers last night, too, conveniently. Bonus.

**Comment by kitsuta** [comment]
Oh yes, just realized while testing that group leaders can actually grant their dealer assistants accounts through the homepage, e.g., 
![image](https://user-images.githubusercontent.com/7198215/133498810-da0d1ebc-d497-44f5-a875-880c33afbfc1.png)

So the link will only appear if the group leader actually has access to the badge, since granting an account hands over control of that badge.

**Comment by fursuit69** [comment]
Is that a thing that was already in place? I'm not seeing it anywhere when I look through screens from a user perspective.

**Comment by kitsuta** [comment]
This did exist already but wasn't showing up for dealers because assigning badges in their group was (erroneously) not adding those badges to their account. It will also show up for anyone who manages multiple regular badges, like (on staging) redirectemail@example.com's account (Password1!).

**Comment by fursuit69** [comment]
Aaaaah okay. I see it under the redirectemail@example.com account. Neat. So I should be expecting something similar under the dealer group master badge holder when updated. My test dealer group for that is exampledealer@furfest.org (Furfest21!)
