### ISSUE TITLE
Attendees checking out can see other attendees registrations

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#415]
The problem is that people are going to register, and they're seeing other people's registration information in their page, and are then being charged for multiple registrations.

**Comment by kitsuta** [comment]
This is https://github.com/MidwestFurryFandom/rams/issues/393 without the % sign (which was likely random).

Reproduction steps:
1. Starting with browser A, fill out `/preregistration/form` and submit to get to `/preregistration/index`.
2. In browser B, fill out `/preregistration/form` and submit to get to `/preregistration/index`.
3. In browser A, enter your account password and start a Stripe payment, then hit Cancel.
4. In browser B, refresh the index page. Now you have browser A's attendee!
5. Bonus: Fill out another preregistration in browser C. You should have both your attendee and browser A's attendee.
