### ISSUE TITLE
Registration: Badges with status set to "Invalid" stay on account holder's list of badges + single invalid badge login flow

### ISSUE THREAD

**Issue by fursuit69** [MidwestFurryFandom/rams#416]
Probably not that big of a thing but could lead to attendee confusion (especially given the badges I just invalidated with the billing bug).

1. A user creates their badge and login account
2. An admin marks the badge "invalid"
3a. If ONLY the invalid badge is held by that user account and the user attempts to login, the login is successful BUT it goes to the "Invalid Badge" notification screen with no guidance (ie click here to go to your account management, etc) on what to do next. (see screenshot). I believe this is because it tries to go directly to the badge management screen instead of the account management screen when only a single badge is involved.
3b. If the user account holds multiple badges, the login goes directly to the account management screen as expected (even if all badges are invalidated). 
4. Invalid badges are still listed and look like normal badges in the user's list of badges. Buttons for marketplace/art show/etc are still active. This may lead to user confusion if they select the wrong badge while trying to sign up for these things. See screenshot.

Recommendations: 

A. Remove invalidated badges entirely from list of user badges. 

B. Gray out the invalidated badges so the user knows they were still there but they can't be clicked or interacted with in any way.

C. Keep the badge list but add a column for "status" that shows the badge status (pending/complete/refunded/invalid). 

Notes:  It's cool that it keeps the user accounts, so at least that doesn't turn into a headache if I ditch their one and only badge. If I "refund" a badge instead of making it "invalid" the process is neat as well - It will pop up a box upon login saying that their badge was refunded and that they can make it again, and it will reinsert their info. Nice. Then they pay as normal.

Regarding the 9/15 Launch issue with the large set of refunds, I am leaving those badges set invalid because it is difficult to tell whose badge was actually the paid one versus whose wasn't, and so-forth. So the above 1-4 applies.

![InvalidRegScreen](https://user-images.githubusercontent.com/90427815/133547442-e8d61b7a-245b-4f64-8652-c5a674cc9ea9.png)

![InvalidRegList](https://user-images.githubusercontent.com/90427815/133547771-1f016013-fbfe-4fac-85cf-9458478191ac.png)

**Comment by kitsuta** [comment]
New behavior:
1. Attendees whose accounts have only a single badge don't get redirected if that badge is invalid
2. Invalidated badges are not shown on the homepage
3. Valid or potentially valid badges have their status shown in a column next to them -- this includes New, Complete, Pending, and On Hold badges
4. Refunded and Deferred badges are in a separate table called "Cancelled Registrations" that do not include the confirmation page links or the art show/marketplace app buttons
5. Refunded badges have a "Repurchase" button next to them

Is it okay to show Pending and On Hold badges? If we remove them, attendees might get confused about their registration not existing, but if we keep them, attendees might ask what Pending or On Hold means. If we hide them, then I'll probably also remove the Status column I added.

**Comment by fursuit69** [comment]
Confirmation of new behavior:

1. Works great, I like it.
2. Confirmed, invalidated badges are hidden.
3. I see all of those, good.
4. Yes, those statuses are good and show up in the "cancelled registrations" table.
5. Yes, this works.

Great!  We can leave pending and On Hold in place.
