### ISSUE TITLE
Dealers are getting 500 error about badge number when registering

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#417]
<img width="751" alt="Screen Shot 2021-09-16 at 14 53 03" src="https://user-images.githubusercontent.com/910490/133677073-8533e88c-5ba1-4184-9f85-33d584328dbf.png">

I have verified that other dealers have the badge number in question. I have at least 3 reported cases of this happening, possibly 5 so far.

**Comment by kitsuta** [comment]
This is the same bug as https://github.com/MidwestFurryFandom/rams/issues/333 -- we're going to try to catch the exception and re-roll the badge number and hopefully that will fix this without having to reproduce it.

**Comment by jmdawson** [comment]
We undid this for now w/ not assigning badge numbers right away.
