### ISSUE TITLE
Clicking "I use my home address as my business address" causes dealer form to fail

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#424]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/910490/133871610-74134ed0-d88f-420e-843e-15f5e3f37d33.png">

**Comment by kitsuta** [comment]
Interesting -- this definitely worked while I was testing on my local environment, but I just confirmed it's not working on staging at all.

**Comment by jmdawson** [comment]
Uncommitted change? I got that from my local.
