### ISSUE TITLE
 Syntax error viewing dealer page from admin side

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#426]
Uncaught SyntaxError: expected expression, got ','form:736:35

```
$(function() {
      $("select[name=tables]").on('change', updateBadgeMax);
      updateBadgeMax();
      var selectedBadge = Math.min(, $('select[name=badges] option:last').val());
      $('select[name=badges] option[value="' + selectedBadge + '"]').prop('selected', true);
  });
```

**Comment by jmdawson** [comment]
![Uploading image.png…]()

**Comment by kitsuta** [comment]
Looks like we're missing our `{{ badges }}` variable in that context: https://github.com/MidwestFurryFandom/rams/blob/mff-staging/uber/templates/fields/group.html#L125

**Comment by jmdawson** [comment]
Fixed in https://github.com/MidwestFurryFandom/rams/commit/533ee368e5419494cfd3dd741d38e6ccdc893c75
