### ISSUE TITLE
Statistics Pages are missing

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#427]
Accessing `http://rams.test.furfest.org/rams/reg_reports/` (prod and staging both). Same w/ Badges Sold
```
404 Not Found
The path '/rams/reg_reports/' was not found. 
```

<img width="170" alt="image" src="https://user-images.githubusercontent.com/910490/133942325-cde0fdf4-806e-4358-a0ff-0839546f079c.png">

**Comment by kitsuta** [comment]
Whoops! I think these are the links you need:
http://rams.test.furfest.org/rams/statistics/index
http://rams.test.furfest.org/rams/statistics/badges_sold
