### ISSUE TITLE
Sometimes an Attendee's Account can be deleted by surprise

### ISSUE THREAD

**Issue by SelenetheCorgi** [MidwestFurryFandom/rams#432]
### Attendee States Cannot Log into Account - Email Verified
[Redacted] - [Redacted]

Cannot log into RAMS account using the above email. He stated he has tried it with all lower case letters and has attempted on multiple devices. He has tried to reset his password, but he keeps getting the error that his email does not exist.

Please review the logs and see why he is having an issue with resetting his password/logging in.

**Comment by jmdawson** [comment]
The attendee's account was deleted -- this appears to be the result of a defect.
