### ISSUE TITLE
Some dealers don't see the Art Show or Marketplace buttons in their account view

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#442]
Dealer A reports they cannot see the Art Show Application button or the Artist Marketplace button in their account view. Artist B reports they can. I have not duplicated this yet.

**Comment by Hugmonster** [comment]
Tested  and found the issue was related to groups.  Had Artist B access their group and then the member and they did see the application and apply successfully.  See email for details

**Comment by kitsuta** [comment]
Estimate: 3 hours to do a full test plan for the accounts page, similar to what I did for the sponsor button. That should prevent this and any other strange issues where someone's view of their account isn't what we would expect it to be.

**Comment by kitsuta** [comment]
This should effectively be fixed by improvements I made to the account/confirmation page workflow this year -- I simplified it and gave everyone a big "homepage" button so they could always go to the account-based view from any other view. We can re-open this if people still have issues.
