### ISSUE TITLE
As an Art Show staffer, I'd like the character bid sheet to print if the name has non-latin characters 

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#449]
Apparently a PDF parser issue. Still is an issue sometimes.
https://github.com/MidwestFurryFandom/art_show/issues/247

**Comment by kitsuta** [comment]
So far we've had problems with `’` preventing bid sheets from printing. Easy to work around by renaming them with `'` instead, but annoying. Here's the error:
```
'latin-1' codec can't encode character '\u2019' in position 273: ordinal not in range(256)
```

**Comment by kitsuta** [comment]
Estimate: 1 hour to prevent non-latin characters. MUST be done before art apps start being accepted.
