### ISSUE TITLE
Some art show pieces did not get paid status after being paid

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#455]
jmdawson commented on Dec 8, 2019

GOL-2 (fefd4ae6-9a63-4284-b026-bb3a9761e609) and DIA-7 (fe961a5c-3a38-4a31-a3b7-d58de03f8cb0) both ended up w/ sold (107404813) status even though they have associated receipts and other pieces on those receipts are listed as paid (110959155)
@Hugmonster
Hugmonster commented on Jul 24

Only happen with one piece and I think it was affected by changes in process, possibly multi work stations had same item open.
https://github.com/MidwestFurryFandom/art_show/issues/293

**Comment by kitsuta** [comment]
We do not think this is still happening.
