### ISSUE TITLE
As someone checking in an artist, I need ALL their pieces displayed on the form

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#456]
> When I made the table of pieces in the check-in/out form a Datatable, I overlooked the fact that our DataTables are set to only show 25 rows at a time. All an artist's pieces should be shown on that form without an admin having to change the view; among other things, they don't all get set to 'hung' if they're not all displayed.

>Need to fix for 2020 as it added a lot of headaches throughout the weekend.

https://github.com/MidwestFurryFandom/art_show/issues/290

**Comment by Hugmonster** [comment]
This is my #2 Priority to have before convention as it can cause additional work  at con.    Might be as easy as changing the default dropdown to all for the Check in and Check out Screens.   
![image](https://user-images.githubusercontent.com/39575926/137232242-3e45491f-9188-4e05-a485-fc8d58a558cb.png)

**Comment by Hugmonster** [comment]
Adding Due Date of 12/1

**Comment by kitsuta** [comment]
This didn't actually get fixed, much to my chagrin.
