### ISSUE TITLE
Unable to view or edit attendee badge name on Attendee Information page

### ISSUE THREAD

**Issue by adebus** [MidwestFurryFandom/rams#458]
The main attendee information page (/rams/registration/form) does not offer any way to view or edit an attendee's printed badge name. 

The name can be viewed in the main attendee list, however, that offers no way to edit it. 

Additionally, if you have to search (Because there are thousands of registrants) but the person you are searching for is the only person with that name, you will be placed directly on the attendee information page, and returning to the list will present you with the full list instead of just the one.

The ability to view and edit badge names is essential for two reasons:

1) We try and keep a proactive eye out for potentially offensive names to address them before they get printed.

2) Some number of attendees will decide they wish to change their badge name mid-con, and will request that registration update and reprint their badge (surrendering their old badge in the process).

**Comment by kitsuta** [comment]
The attendee form is a little crowded, but the badge name is called "Name Printed on Badge" and is right under the "Name as appears on Legal Photo ID."

**Comment by adebus** [comment]
Hi Kit, 

I don't see that at all on Staging or Prod:

Staging:

![image](https://user-images.githubusercontent.com/4514884/137003032-f93f889d-b1ee-4ef0-b737-93a2d6a6eea9.png)

Prod:

![image](https://user-images.githubusercontent.com/4514884/137003268-df3fe897-96a3-48e0-9297-c85087428b95.png)


However, what's interesting, is that in prod, for my personal account, the "Name on Badge" field appears:


![image](https://user-images.githubusercontent.com/4514884/137003401-9694e2ea-0cad-4403-849c-4cf6fe4a2989.png)

It's not filled in, becuase this was the admin account that was created for me, but it's interesting that it appears in one attendee form, but not another.
