### ISSUE TITLE
Completion of badge upgrade leave user on upgrade selection page

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#49]
Upgraded a badge, but after strip completed, it showed a nice top banner, but left me on the upgrade page.
![stillonpage](https://cloud.githubusercontent.com/assets/910490/25032077/f25d4188-2096-11e7-9920-78c3626cb611.jpeg)

**Comment by kitsuta** [comment]
Note: suggestion is that it goes to a payment confirmation page, making it more obvious that the payment was completed. Said page should link to the attendee confirmation page.
