### ISSUE TITLE
Art Show Bid Sheets need adjustments 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/rams#492]
Bid sheets are cut off on the left and right Margins.  Need a smaller vertical Gutter.  
Also need a larger barcode.  
![photo_2021-11-11_17-46-39](https://user-images.githubusercontent.com/39575926/141380458-066557a3-1442-4460-a5af-7faa1cd1a9dc.jpg)
![BarCodeSizecomparte201922021_LI](https://user-images.githubusercontent.com/39575926/141380466-aa08077c-565d-4dcb-ac57-ad4975ce963f.jpg)
![FullSizeBidSheetPrint2021](https://user-images.githubusercontent.com/39575926/141380478-9c92ca39-3fd0-47c4-a6a5-7881989ecf03.jpg)

**Comment by kitsuta** [comment]
I can't reproduce these issues on my end.
![image](https://user-images.githubusercontent.com/7198215/142363145-57c98abe-ca3c-4670-bb67-f13f7e35024d.png)

I think the shorter barcode you found in test was due to a shorter artist code (e.g., M-4 instead of TWO-2)

**Comment by Hugmonster** [comment]
Ok.. I figured out the cut off issue.  I was not shrinking to fit in
Adobe.  I did now and we are good to go.  I just have to remember to do
that at Con.

Hugmonster
Art Show Director

**Comment by Hugmonster** [comment]
This issue is closed.  Issue was I was not printing with the correct settings
