### ISSUE TITLE
As an attendee, I want to cancel my badge without having my information deleted

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#5]

**Comment by kitsuta** [comment]
Question: what happens to the attendee's money when they cancel their badge? Should admins be notified of badge cancellations?

**Comment by ianlayton** [comment]
To clarify, badge cancellation is an registration admin function only. An attendee that would want to cancel a badge would need to email us to request the cancellation. At that point, we deal with the money transaction separately. 

What I want to make sure that can happen is say if person A requests a cancellation on June 1 and the admin does it, that they can come back and repurchase a membership down the road if they wish, but any records of their previous registration isn't removed.

**Comment by kitsuta** [comment]
Ah, okay! That's easy -- I'll just get rid of the Delete button to make sure admins don't accidentally remove badges from the system.

**Comment by ianlayton** [comment]
Well...we still need to flag the badge as cancelled somehow. Is that still possible?

**Comment by kitsuta** [comment]
Yup! That can be done with flags on the badges called 'badge statuses' -- the canonical badge status for cancelled/refunded badges is `Refunded` for MAGFest, but you can also use `Invalid` badge or `Deferred` badge. I'll make a note to myself here to write up some quick user documentation for how those work and what they do in the system. Only badges with a `Complete` status may be checked in.

**Comment by ianlayton** [comment]
That works for me. We'll have to make sure stats take that into account (or at least I need to know if stats do take that into account)

**Comment by kitsuta** [comment]
Fixed by the commit referenced above.
