### ISSUE TITLE
Appear to be past badge print deadline

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#52]
I didn't validate the file's dates there, but behavior suggest we are:
>Badge names have a maximum of 20 characters.
>(custom badges have already been ordered, so you can no longer set this)

**Comment by kitsuta** [comment]
Yeah, my development.ini has it set as `printed_badge_deadline = "2016-01-04"` so yours probably does too. Whoops.

**Comment by kitsuta** [comment]
We've now fixed the config on this.
