### ISSUE TITLE
Investigate way to make marking refunded memberships easier

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#535]
Currently, there appears to be at least 4 different steps on multiple screens to making sure a refund is handled and flagged correctly in the system. To simplify workflow and make sure all places that should be marked are marked as such, we should look at implementing an single button solution that would do the following:

1. Mark the badge itself as "Refunded"
2. Mark the overall payment status as "Paid and Refunded"
3. Mark the payment itself as refunded
4. Issue a refund command to Stripe for the payment via their API (if possible)

Interface would be a button that says "Refund and Invalidate Registration" on the main information screen for the registration. Possibly a warning popup that would explain exactly what's being done and ask for confirmation.

Obviously, this should be restricted to the higher level registration admin accounts. For simplicity sake, it can also be limited to registrations that have a single payment attached to them.

**Comment by kitsuta** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/7198215/189897102-6debc2d5-f58b-4645-80f2-c3d6e5a9f77c.png">
We did this!
