### ISSUE TITLE
As a dealer admin, I would like to allow a specific dealer to fill out an application after the deadline has passed

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#55]

**Comment by kitsuta** [comment]
Admins can currently create dealers with minimal info -- just the name of the group, the tables/badges they should have, and the owner's name/email. One could then provide the link to the group members page to the dealer in question. We should review this to make sure it sufficiently solves this user story.

**Comment by kitsuta** [comment]
@jmdawson is this good?

**Comment by jmdawson** [comment]
Yeah, we'll use placeholders for this.
