### ISSUE TITLE
Issues with "Upgrades" and the /rams/preregistration/confirm page

### ISSUE THREAD

**Issue by adebus** [MidwestFurryFandom/rams#572]
I attempted to upgrade a Sponsor to Shiny Sponsor, and am unable to, there is no option to click.

![image](https://user-images.githubusercontent.com/4514884/185705253-90ccae91-d578-4632-a320-48994e97eaac.png)

The only option is to say "no Thanks" to "Kick in extra"

Additionally, we should potentially hide the "Kick-in/Upgrade" and "Kick in extra" options on these pages, as MFF doesn't use them. 

![image](https://user-images.githubusercontent.com/4514884/185705404-31815d88-093a-4823-87d7-83bac1154b25.png)

**Comment by adebus** [comment]
Testing this as an Attendee, I get this modal as expected:

![image](https://user-images.githubusercontent.com/4514884/185705692-1ada453b-d15a-4ef6-8f42-038fc57a2579.png)

However, I still think the "Kick-in/Upgrade" section on the page will cause confusion.

**Comment by adebus** [comment]
![image](https://user-images.githubusercontent.com/4514884/185706833-1703d215-99da-49f1-b7e6-f7c3fe6aa1be.png)

**Comment by kitsuta** [comment]
We've deployed with a fix for the config -- the system was erroneously configured to offer kick-ins, but since there were no kick-in tiers defined, it caused these issues. This should be fixed now.
