### ISSUE TITLE
Upgrading Attendee to Sponsor, page thanks you for purchase, but also indicates you still have an outstanding balance

### ISSUE THREAD

**Issue by adebus** [MidwestFurryFandom/rams#573]
In upgrading an Attendee to Sponsor, I receive the following:

![image](https://user-images.githubusercontent.com/4514884/185706083-c981ed71-3f3c-4504-95c4-615b2f8bac4e.png)

This thanks me for my payment after I enter my credit card, but also indicates I still have an outstanding balance of $100.

I see the payment in stripe:

![image](https://user-images.githubusercontent.com/4514884/185706170-5e75c6d4-aaa5-45b2-8fc2-b4a1e4515756.png)

And in the admin section the attendee is listed as Sponsor:

![image](https://user-images.githubusercontent.com/4514884/185706213-ee6925cd-dc07-4fe1-b3c8-e29a81d36132.png)

Along with the appropriate receipt items:

![image](https://user-images.githubusercontent.com/4514884/185706246-45c034a8-a1ea-41bd-be0d-b229ea2cc7f7.png)

Returning the user to the homepage, correctly shows the user as Sponsor, and going back into details shows the page as expected.

**Comment by kitsuta** [comment]
This behavior is correct but this is a good reminder that we still need to set up the Stripe webhooks on both staging and prod. Based on the fact that the attendee was marked as paid later, it looks like the scheduled task for contacting Stripe without a webhook is working, so that's good.
