### ISSUE TITLE
Determine process for deploying new code w/out destroying DB

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#62]

**Comment by kitsuta** [comment]
This _should_ be a simple `docker-compose restart web` -- that's how I deploy most code on my dev system.

There's no good process for deploying database changes in quickstart, though.

**Comment by jmdawson** [comment]
I think we'll primarily solve this by putting the database into RDS and pointing the web container at it. We'll also disable the PG container in quickstart. This way, quickstart shouldn't be able to break it.

The downside is that when we require DB changes, we'll have to do something to port the data from old DB to new.

**Comment by jmdawson** [comment]
Yup, that's totally how we'll do it.
