### ISSUE TITLE
As registration staff, I want a way to create registrations for deferred badges from last year, staff/volunteers, or other comped attendees

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#7]
This may already be doable -- need to discuss whether the way the current 'placeholder' system works is sufficient.

**Comment by jmdawson** [comment]
We'll need to know more about how the placeholder system works.

**Comment by ianlayton** [comment]
So, the intent here is not necessarily deferred badges, but credits that can be applied to badge purchases. In previous years, for example, for the rollovers for volunteers that accrued enough hours, I would go into the system and apply a $50 credit on the account for the volunteer. They could then log into the account when they wanted to, fill out their registration and have the $50 applied to the price. For standard registrations, this would cover the full cost of the registration and they wouldn't be shared. If they wanted to get a sponsor level, it would prompt the user for the difference in the cost.

It sounds like the deferred badge system can be used for this. For someone that wanted a sponsor level, the person would have to go through another step to upgrade, which is fine. Only applies to maybe 5% of the people that gets these comps.

**Comment by kitsuta** [comment]
Great! I think the current tools of the system should satisfy MFF's use-cases -- you can definitely do things like change attendee's badge prices, manually mark them as having paid an arbitrary amount, and even give them a special 'need not pay' status (for free badges). We'll want to review exactly how those tools work for your benefit at some point, but the system shouldn't need any changes.
