### ISSUE TITLE
As a young attendee, I would like age-based prices to be available online

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#71]
RAMS has the capability to automatically apply a set discount (say, $10 off) to badges based on an attendee's age. It can also make badges free (by applying a $9999 discount). I noticed that the page at https://www.furfest.org/registration says that 7-12 discounts and free badges for children aren't available online, but we can easily _make_ them available and that tends to be very good for attendees.

@ianlayton this is up to you regarding policy. It's a simple set of config options if we want to do it.

**Comment by ianlayton** [comment]
Let's leave it off at this time. The vast majority of people that are
discounted are simply day badges, not full weekend. I'm not sure it's worth
having to have the extra step of reg people having to verify that someone
isn't buying a discounted badge when they shouldn't for the maybe half
dozen that would use it. However, if it's something where I can set up a
registration to the minor discount (ie someone emails me, saying they want
it, I do some magic and make it available to them only, much like a comped
membership) that would be great.
