### ISSUE TITLE
As an attendee used to only entering my name once, I want the Legal Name field to be less confusing

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#72]
The legal name field is new and several people have reporting it causing them confusion. We can potentially update the wording on it and UI around it to make it clearer that its purpose is to match your photo ID exactly for check-in.

By the way, we used to simply tell people that their first and last name must match their photo ID. It didn't work for most people but it DID end up making our automated emails deadname anyone whose driver's license had the wrong name. We can hide/disable it if MFF really wants but I recommend keeping it.

**Comment by ianlayton** [comment]
Can we maybe repurpose it to be called "preferred name", so legal name on
the ID is still in the form, but if they go by a different name (ie in the
middle of a transition) then we can record it

**Comment by kitsuta** [comment]
That's a bigger change than it seems at first, because it we'd have to refactor `first_name` out of all our emails and other places it is displayed. Otherwise we'd ask people their preferred name and then not actually use it. :/

**Comment by ianlayton** [comment]
Personally, the form looks confusing on this as what your legal name is
should be on your ID. But...if MagFest isn't seeing people getting confused
by it, we can leave it. How hard would it be to turn it off later if this
causes more confusion then it's worth?

**Comment by kitsuta** [comment]
Just as an update, we're going to aim for a UI-based fix to make it seem less confusing.
