### ISSUE TITLE
Hide unnecessary fields on the pre-reg page

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#74]
MFF does not want:
- What interests you?
- How did you find us?
- Comments
- Keep me updated

For the last field, we also want to make sure to also set it to False in a presave adjustment, so we don't accidentally secretly set it to true.

**Comment by ianlayton** [comment]
Just a clarification, I would like the comment field available for admins
to fill in, just not for the registering person to fill in.

**Comment by jmdawson** [comment]
There is an admin notes field available already.
