### ISSUE TITLE
As registration staff, I want to be able to see who qualifies for a comped badge and who has claimed their comped badge

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#8]

**Comment by kitsuta** [comment]
Question: will registration staff need or want to view placeholder badges 'by type' -- i.e., is it important to be able to filter this report based on _why_ the attendee has a comped badge? Will we need other info in this report, like who created the comped badge and when, if the comped attendee bought any upgrades, etc? Should placeholder badges require a reason/admin note for being created?

**Comment by ianlayton** [comment]
Having a reason recorded for a comped badge would be helpful.

**Comment by kitsuta** [comment]
Roger! Good to know.

**Comment by kitsuta** [comment]
Oof, terrible name for a commit but this was indeed fixed by https://github.com/MidwestFurryFandom/mff-rams-plugin/commit/3a3f1c515d88b06716df6b2e66235707e8ddb19d.
