### ISSUE TITLE
As an admin, I want to know if changing an email template will cause all queued emails to change as well

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#84]

**Comment by jmdawson** [comment]
We need to get email set up to determine this, right?

**Comment by kitsuta** [comment]
Yeah, I don't think they'll queue otherwise.

**Comment by jmdawson** [comment]
Email is running on all the systems, so now I need to figure out how to test this.

**Comment by kitsuta** [comment]
Take an email that has at least one 'email waiting to be sent' in the pending queue, like http://rams.test.furfest.org/rams/emails/pending_examples?ident=regular_badge_confirmation. Find its template and change it, then restart the server and see if those examples change or not.

**Comment by jmdawson** [comment]
Tests indicate that emails in pending state will be sent out with whatever the current state of the template is _at the time of sending_.  So, if an email is queued for sending, but not approved until after a template is updated, they will be sent with the 'new' template.

**Comment by kitsuta** [comment]
Oh good! That works as we want it to, then.
